# Lab 3
## More EDA: improving expertise in loading, cleaning, and analyzing data

The objective of Lab 3 is for you to become more proficient in obtaining and working with different types of data. A particular emphasis will be on dealing with text data.

This lab assignment will have 3 components. 

## Lab 3.A. Complete tutorials from Harvard's CS109 Lab 1

Go to https://github.com/cs109/2015lab1 and download the following files in your local Lab3 directory:
- https://github.com/cs109/2015lab1/blob/master/all.csv
- https://github.com/cs109/2015lab1/blob/master/hamlet.txt

We are going to go through the *Lab1-babypython.ipynb* and *Lab1-pythonpandas.ipynb*. The orginal Python notebooks were written in Python 2. We converted the notebooks into Python 3, which can be downloaded from here"

- https://github.com/CIS3715-temple-2019/CIS3715-temple-2019.github.io/blob/master/CIS3715-Lab3.A-babypython_py3.ipynb
- https://github.com/CIS3715-temple-2019/CIS3715-temple-2019.github.io/blob/master/CIS3715-Lab3.A-pythonpandas_py3.ipynb

Study all the code and run every block of code from the *babypython* tutorial. It covers many of the things you already learned in your Labs 1 and 2, so it is a good refresher. However, there are some new things. In particular, you will learn how to load a pure textual file and process it to find counts of all the unique words (also called the tokens) in the text.

Study all the code and run every block of code from the *pythonpandas* tutorial. Again, you will find there many things you already know. However, the novelty here is in processing and analysis of a slightly messy tabular data than was the case with the *Auto MPG data*.



**Deliverable**: submit the two .ipynb files after you have run all the lines of code. We will appreciate if we see that you put some extra effort, such as trying to modify existing code, enter new lines of code, or provide comments in the text. Make sure any modifications are easily visible by us for the grading purposes.

## Lab 3.B. Movie Lens Data

In this part of the lab, you will be working on an exercise that is a slightly modified and shortened version of https://github.com/cs109/2015/blob/master/Lectures/02-DataScrapingQuizzes.ipynb. In particular, you will learn how to load and analyze MoviLens data, which contains ratings of multiple movies by multiple users.

**The MovieLens data**

http://grouplens.org/datasets/movielens/

Take some time to learn about the data, because it will be helpful to do the assignment.

In [10]:
## all imports
from IPython.display import HTML
import numpy as np
import requests
import bs4 #this is beautiful soup
import time
import operator
import socket
import re # regular expressions

from pandas import Series
import pandas as pd
from pandas import DataFrame

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# Read the user data:
#   pass in column names for each CSV
u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']

users = pd.read_csv(
    'http://files.grouplens.org/datasets/movielens/ml-100k/u.user', 
    sep='|', names=u_cols, engine='python')

users.head(20)

    user_id  age sex     occupation zip_code
0         1   24   M     technician    85711
1         2   53   F          other    94043
2         3   23   M         writer    32067
3         4   24   M     technician    43537
4         5   33   F          other    15213
5         6   42   M      executive    98101
6         7   57   M  administrator    91344
7         8   36   M  administrator    05201
8         9   29   M        student    01002
9        10   53   M         lawyer    90703
10       11   39   F          other    30329
11       12   28   F          other    06405
12       13   47   M       educator    29206
13       14   45   M      scientist    55106
14       15   49   F       educator    97301
15       16   21   M  entertainment    10309
16       17   30   M     programmer    06355
17       18   35   F          other    37212
18       19   40   M      librarian    02138
19       20   42   F      homemaker    95660

In [7]:
# Read the ratings:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv(
    'http://files.grouplens.org/datasets/movielens/ml-100k/u.data', 
    sep='\t', names=r_cols, engine='python')

ratings.head(20)

    user_id  movie_id  rating  unix_timestamp
0       196       242       3       881250949
1       186       302       3       891717742
2        22       377       1       878887116
3       244        51       2       880606923
4       166       346       1       886397596
5       298       474       4       884182806
6       115       265       2       881171488
7       253       465       5       891628467
8       305       451       3       886324817
9         6        86       3       883603013
10       62       257       2       879372434
11      286      1014       5       879781125
12      200       222       5       876042340
13      210        40       3       891035994
14      224        29       3       888104457
15      303       785       3       879485318
16      122       387       5       879270459
17      194       274       2       879539794
18      291      1042       4       874834944
19      234      1184       2       892079237

In [204]:
# Read the movies data
#  the movies file contains columns indicating the movie's genres
#  let's only load the first five columns of the file with usecols
m_cols = ['movie_id', 'title', 'release_date', 
            'video_release_date', 'imdb_url']

movies = pd.read_csv(
    'http://files.grouplens.org/datasets/movielens/ml-100k/u.item', sep='|', encoding = "ISO-8859-1", names=m_cols, usecols=range(5), engine='python')

movies

,movie_id,title,release_date,video_release_date,imdb_url
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995)
5,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,01-Jan-1995,NaN,http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...
6,7,Twelve Monkeys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Twelve%20Monk...
7,8,Babe (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Babe%20(1995)
8,9,Dead Man Walking (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Dead%20Man%20...
9,10,Richard III (1995),22-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Richard%20III...
10,11,Seven (Se7en) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Se7en%20(1995)
11,12,"Usual Suspects, The (1995)",14-Aug-1995,NaN,http://us.imdb.com/M/title-exact?Usual%20Suspe...
12,13,Mighty Aphrodite (1995),30-Oct-1995,NaN,http://us.imdb.com/M/title-exact?Mighty%20Aphr...
13,14,"Postino, Il (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Postino,%20Il..."
14,15,Mr. Holland's Opus (1995),29-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Mr.%20Holland...
15,16,French Twist (Gazon maudit) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Gazon%20maudi...
16,17,From Dusk Till Dawn (1996),05-Feb-1996,NaN,http://us.imdb.com/M/title-exact?From%20Dusk%2...
17,18,"White Balloon, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Badkonake%20S...
18,19,Antonia's Line (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Antonia%20(1995)
19,20,Angels and Insects (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Angels%20and%...
20,21,Muppet Treasure Island (1996),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Muppet%20Trea...
21,22,Braveheart (1995),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Braveheart%20...
22,23,Taxi Driver (1976),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Taxi%20Driver...
23,24,Rumble in the Bronx (1995),23-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Hong%20Faan%2...
24,25,"Birdcage, The (1996)",08-Mar-1996,NaN,"http://us.imdb.com/M/title-exact?Birdcage,%20T..."
25,26,"Brothers McMullen, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Brothers%20Mc...
26,27,Bad Boys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Bad%20Boys%20...
27,28,Apollo 13 (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Apollo%2013%2...
28,29,Batman Forever (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Batman%20Fore...
29,30,Belle de jour (1967),01-Jan-1967,NaN,http://us.imdb.com/M/title-exact?Belle%20de%20...
...,...,...,...,...,...
1652,1653,Entertaining Angels: The Dorothy Day Story (1996),27-Sep-1996,NaN,http://us.imdb.com/M/title-exact?Entertaining%...
1653,1654,Chairman of the Board (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Chairman+of+the+Board...
1654,1655,"Favor, The (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Favor,%20The%..."
1655,1656,Little City (1998),20-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Little+City+(...
1656,1657,Target (1995),28-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Target%20(1995)
1657,1658,"Substance of Fire, The (1996)",06-Dec-1996,NaN,http://us.imdb.com/M/title-exact?Substance%20o...
1658,1659,Getting Away With Murder (1996),12-Apr-1996,NaN,http://us.imdb.com/Title?Getting+Away+With+Mur...
1659,1660,Small Faces (1995),09-Aug-1996,NaN,http://us.imdb.com/M/title-exact?Small%20Faces...
1660,1661,"New Age, The (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?New%20Age,%20..."
1661,1662,Rough Magic (1995),30-May-1997,NaN,http://us.imdb.com/M/title-exact?Rough%20Magic...
1662,1663,Nothing Personal (1995),30-Apr-1997,NaN,http://us.imdb.com/M/title-exact?Nothing%20Per...
1663,1664,8 Heads in a Duffel Bag (1997),18-Apr-1997,NaN,http://us.imdb.com/Title?8+Heads+in+a+Duffel+B...
1664,1665,"Brother's Kiss, A (1997)",25-Apr-1997,NaN,http://us.imdb.com/M/title-exact?Brother%27s%2...
1665,1666,Ripe (1996),02-May-1997,NaN,http://us.imdb.com/M/title-exact?Ripe%20%28199...
1666,1667,"Next Step, The (1995)",13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Next%20Step%2...
1667,1668,Wedding Bell Blues (1996),13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Wedding%20Bel...
1668,1669,MURDER and murder (1996),20-Jun-1997,NaN,http://us.imdb.com/M/title-exact?MURDER+and+mu...
1669,1670,Tainted (1998),01-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Tainted+(1998)
1670,1671,"Further Gesture, A (1996)",20-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Further+Gestu...
1671,1672,Kika (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Kika%20(1993)
1672,1673,Mirage (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Mirage%20(1995)
1673,1674,Mamma Roma (1962),01-Jan-1962,NaN,http://us.imdb.com/M/title-exact?Mamma%20Roma%...
1674,1675,"Sunchaser, The (1996)",25-Oct-1996,NaN,"http://us.imdb.com/M/title-exact?Sunchaser,%20..."
1675,1676,"War at Home, The (1996)",01-Jan-1996,NaN,http://us.imdb.com/M/title-exact?War%20at%20Ho...
1676,1677,Sweet Nothing (1995),20-Sep-1996,NaN,http://us.imdb.com/M/title-exact?Sweet%20Nothi...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998)
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...

Get information about the data:

In [83]:
movies['release_date'] = movies.release_date.astype('datetime64') # converted the dtype of release_date from object -> datetime64
print(movies.dtypes)
print()
print(movies.describe())
# *** Why only those two columns? ***

movie_id                       int64
title                         object
release_date          datetime64[ns]
video_release_date           float64
imdb_url                      object
dtype: object

          movie_id  video_release_date
count  1682.000000                 0.0
mean    841.500000                 NaN
std     485.695893                 NaN
min       1.000000                 NaN
25%     421.250000                 NaN
50%     841.500000                 NaN
75%    1261.750000                 NaN
max    1682.000000                 NaN

Selecting data:

* DataFrame => group of Series with shared index
* single DataFrame column => Series

In [113]:
users.head()
print("hello")
users['occupation'].head()
## *** Where did the nice design go? ***
columns_you_want = ['occupation', 'sex'] 
users[columns_you_want].head()

hello

   occupation sex
0  technician   M
1       other   F
2      writer   M
3  technician   M
4       other   F

Filtering data:

Select users older than 25

In [ ]:
oldUsers = users[users.age > 25]
oldUsers.head()

**Question 1**: 
* show users aged 40 and male
* show the mean age of female programmers

In [107]:
# users aged 40 AND male
oldUsers = users[(users.age == 40) & (users.sex == 'M')] # users aged 40 and male
print(oldUsers)

## users who are female and programmers
female = users[(users.sex == "F") & (users.occupation == "programmer")] 
## show statistic summary or compute mean
print("mean age of female programmers is", np.mean(female.age))  # mean age of female programmers

     user_id  age sex  occupation zip_code
18        19   40   M   librarian    02138
82        83   40   M       other    44133
115      116   40   M  healthcare    97232
199      200   40   M  programmer    93402
283      284   40   M   executive    92629
289      290   40   M    engineer    93550
308      309   40   M   scientist    70802
357      358   40   M    educator    10022
397      398   40   M       other    60008
564      565   40   M     student    55422
646      647   40   M    educator    45810
791      792   40   M  programmer    12205
841      842   40   M      writer    93055
917      918   40   M   scientist    70116
mean age of female programmers is 32.166666666666664

Find Diligent Users

- split data per user ID
- count ratings
- combine result

In [ ]:
print(ratings.head())
## split data
grouped_data = ratings.groupby('user_id')
#grouped_data = ratings['movie_id'].groupby(ratings['user_id'])

## count and combine
ratings_per_user = grouped_data.count()

ratings_per_user.head(5)

**Question 2**:
* get the average rating per movie
* advanced: get the movie titles with the highest average rating

In [260]:
## split data
movie_id_and_rating = ['movie_id', 'rating']
a = ratings[movie_id_and_rating]
sorted_a = a.sort_values(by=['movie_id'])
arr = np.array([])
num_of_ratings_per_movie = []

## average and combine
for i in range(1,1683):
    mean = np.mean(sorted_a[sorted_a.movie_id == i].rating)
    num_of_ratings_per_movie.append(np.sum(sorted_a[sorted_a.movie_id == i].rating))
    arr = np.append(arr, mean)

# displays the movie title and the average rating alongside of it
for i,v in enumerate(arr,1):
    name_of_movie = movies[movies.movie_id == i]
    print(movies[movies.movie_id == i].title, "-- AVERAGE RATING OF MOVIE = ", v)

# get the maximum rating
max_rate = np.amax(arr)
print("MAXIMUM RATING IS ", max_rate)
# your code here

# get movie ids with that rating (anything higher than 4.8)
high_rated = np.where(arr > 4.8)
high_rated = high_rated[0]
l = np.ndarray.tolist(high_rated)
print()
print()
for i in l:
    print(movies[movies.movie_id == i].title, "****** HAS A HIGH RATING *******")

print()
print()
print("Good movie ids:")
for i in l:
    print(i, "****** GOOD MOVIE IDS *******")

print()
print()

print("Best movie titles")
for i in l:
    print(movies[movies.movie_id == i].title, "****** BEST MOVIE TITLES *******")


# get number of ratings per movie
print("Number of ratings per movie")
num = enumerate(num_of_ratings_per_movie, 1)
for i,v in num:
    print("movie_id", i, "number of ratings", v)

0    Toy Story (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8783185840707963
1    GoldenEye (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2061068702290076
2    Four Rooms (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.033333333333333
3    Get Shorty (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.550239234449761
4    Copycat (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.302325581395349
5    Shanghai Triad (Yao a yao yao dao waipo qiao) ...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.576923076923077
6    Twelve Monkeys (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.798469387755102
7    Babe (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9954337899543377
8    Dead Man Walking (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8963210702341136
9    Richard III (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.831460674157303
10    Seven (Se7en) (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.847457627118644
11    Usual Suspects, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.385767790262173
12    Mighty Aphrodite (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4184782608695654
13    Postino, Il (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9672131147540983
14    Mr. Holland's Opus (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7781569965870307
15    French Twist (Gazon maudit) (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2051282051282053
16    From Dusk Till Dawn (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.119565217391304
17    White Balloon, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
18    Antonia's Line (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9565217391304346
19    Angels and Insects (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4166666666666665
20    Muppet Treasure Island (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.761904761904762
21    Braveheart (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.151515151515151
22    Taxi Driver (1976)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1208791208791204
23    Rumble in the Bronx (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4482758620689653
24    Birdcage, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4436860068259385
25    Brothers McMullen, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.452054794520548
26    Bad Boys (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1052631578947367
27    Apollo 13 (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.931159420289855
28    Batman Forever (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
29    Belle de jour (1967)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.945945945945946
30    Crimson Tide (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6298701298701297
31    Crumb (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7901234567901234
32    Desperado (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4536082474226806
33    Doom Generation, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7142857142857144
34    Free Willy 2: The Adventure Home (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1818181818181817
35    Mad Love (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1538461538461537
36    Nadja (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
37    Net, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0083333333333333
38    Strange Days (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.264367816091954
39    To Wong Foo, Thanks for Everything! Julie Newm...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8947368421052633
40    Billy Madison (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.081081081081081
41    Clerks (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.804054054054054
42    Disclosure (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
43    Dolores Claiborne (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3417721518987342
44    Eat Drink Man Woman (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.05
45    Exotica (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5555555555555554
46    Ed Wood (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.601503759398496
47    Hoop Dreams (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.094017094017094
48    I.Q. (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3209876543209877
49    Star Wars (1977)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.3584905660377355
50    Legends of the Fall (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.45679012345679
51    Madness of King George, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.769230769230769
52    Natural Born Killers (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.953125
53    Outbreak (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2403846153846154
54    Professional, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.704697986577181
55    Pulp Fiction (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.060913705583756
56    Priest (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
57    Quiz Show (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.645714285714286
58    Three Colors: Red (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0602409638554215
59    Three Colors: Blue (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.015625
60    Three Colors: White (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.864406779661017
61    Stargate (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.141732283464567
62    Santa Clause, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.097560975609756
63    Shawshank Redemption, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.445229681978798
64    What's Eating Gilbert Grape (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5391304347826087
65    While You Were Sleeping (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.549382716049383
66    Ace Ventura: Pet Detective (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0485436893203883
67    Crow, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.417910447761194
68    Forrest Gump (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.853582554517134
69    Four Weddings and a Funeral (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6613545816733066
70    Lion King, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7818181818181817
71    Mask, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.193798449612403
72    Maverick (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.46875
73    Faster Pussycat! Kill! Kill! (1965)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
74    Brother Minister: The Assassination of Malcolm...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
75    Carlito's Way (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4074074074074074
76    Firm, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2781456953642385
77    Free Willy (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4545454545454546
78    Fugitive, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.044642857142857
79    Hot Shots! Part Deux (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.764705882352941
80    Hudsucker Proxy, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5545454545454547
81    Jurassic Park (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7203065134099615
82    Much Ado About Nothing (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0625
83    Robert A. Heinlein's The Puppet Masters (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
84    Ref, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0344827586206895
85    Remains of the Day, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.94
86    Searching for Bobby Fischer (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9057971014492754
87    Sleepless in Seattle (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.539906103286385
88    Blade Runner (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.138181818181818
89    So I Married an Axe Murderer (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0526315789473686
90    Nightmare Before Christmas, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5874125874125875
91    True Romance (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6153846153846154
92    Welcome to the Dollhouse (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7232142857142856
93    Home Alone (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0875912408759123
94    Aladdin (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8127853881278537
95    Terminator 2: Judgment Day (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0067796610169495
96    Dances with Wolves (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.79296875
97    Silence of the Lambs, The (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.28974358974359
98    Snow White and the Seven Dwarfs (1937)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7093023255813953
99    Fargo (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.155511811023622
100    Heavy Metal (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.26027397260274
101    Aristocats, The (1970)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1296296296296298
102    All Dogs Go to Heaven 2 (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8666666666666667
103    Theodore Rex (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.4
104    Sgt. Bilko (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5675675675675675
105    Diabolique (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.887323943661972
106    Moll Flanders (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
107    Kids in the Hall: Brain Candy (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.076923076923077
108    Mystery Science Theater 3000: The Movie (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4307692307692306
109    Operation Dumbo Drop (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5161290322580645
110    Truth About Cats & Dogs, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.485294117647059
111    Flipper (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.45
112    Horseman on the Roof, The (Hussard sur le toit...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.111111111111111
113    Wallace & Gromit: The Best of Aardman Animatio...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.447761194029851
114    Haunted World of Edward D. Wood Jr., The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7333333333333334
115    Cold Comfort Farm (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.824
116    Rock, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.693121693121693
117    Twister (1996)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2150170648464163
118    Maya Lin: A Strong Clear Vision (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.5
119    Striptease (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2388059701492535
120    Independence Day (ID4) (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.438228438228438
121    Cable Guy, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.339622641509434
122    Frighteners, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.234782608695652
123    Lone Star (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.053475935828877
124    Phenomenon (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.557377049180328
125    Spitfire Grill, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.804123711340206
126    Godfather, The (1972)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.283292978208232
127    Supercop (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5384615384615383
128    Bound (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8217054263565893
129    Kansas City (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.260869565217391
130    Breakfast at Tiffany's (1961)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7263157894736842
131    Wizard of Oz, The (1939)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0772357723577235
132    Gone with the Wind (1939)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.871345029239766
133    Citizen Kane (1941)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.292929292929293
134    2001: A Space Odyssey (1968)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.969111969111969
135    Mr. Smith Goes to Washington (1939)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.123809523809523
136    Big Night (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9005847953216373
137    D3: The Mighty Ducks (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5789473684210527
138    Love Bug, The (1969)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.78
139    Homeward Bound: The Incredible Journey (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2131147540983607
140    20,000 Leagues Under the Sea (1954)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
141    Bedknobs and Broomsticks (1971)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0701754385964914
142    Sound of Music, The (1965)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.765765765765766
143    Die Hard (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8724279835390947
144    Lawnmower Man, The (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4461538461538463
145    Unhook the Stars (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
146    Long Kiss Goodnight, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4702702702702704
147    Ghost and the Darkness, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.203125
148    Jude (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
149    Swingers (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.828025477707006
150    Willy Wonka and the Chocolate Factory (1971)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6319018404907975
151    Sleeper (1973)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6341463414634148
152    Fish Called Wanda, A (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.785425101214575
153    Monty Python's Life of Brian (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7471264367816093
154    Dirty Dancing (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1020408163265305
155    Reservoir Dogs (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9864864864864864
156    Platoon (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6929133858267718
157    Weekend at Bernie's (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6166666666666667
158    Basic Instinct (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.227722772277228
159    Glengarry Glen Ross (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.463768115942029
160    Top Gun (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.481818181818182
161    On Golden Pond (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.556603773584906
162    Return of the Pink Panther, The (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5543478260869565
163    Abyss, The (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.589403973509934
164    Jean de Florette (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.109375
165    Manon of the Spring (Manon des sources) (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.120689655172414
166    Private Benjamin (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.955223880597015
167    Monty Python and the Holy Grail (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0664556962025316
168    Wrong Trousers, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.466101694915254
169    Cinema Paradiso (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1735537190082646
170    Delicatessen (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.876923076923077
171    Empire Strikes Back, The (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.204359673024523
172    Princess Bride, The (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.172839506172839
173    Raiders of the Lost Ark (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.252380952380952
174    Brazil (1985)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8173076923076925
175    Aliens (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9471830985915495
176    Good, The Bad and The Ugly, The (1966)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8613138686131387
177    12 Angry Men (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.344
178    Clockwork Orange, A (1971)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.909502262443439
179    Apocalypse Now (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.04524886877828
180    Return of the Jedi (1983)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.007889546351085
181    GoodFellas (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9513274336283186
182    Alien (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.034364261168385
183    Army of Darkness (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4310344827586206
184    Psycho (1960)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.100418410041841
185    Blues Brothers, The (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8366533864541834
186    Godfather: Part II, The (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.186602870813397
187    Full Metal Jacket (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6823529411764704
188    Grand Day Out, A (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.106060606060606
189    Henry V (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.137096774193548
190    Amadeus (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.163043478260869
191    Raging Bull (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.120689655172414
192    Right Stuff, The (1983)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.917197452229299
193    Sting, The (1973)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.058091286307054
194    Terminator, The (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9335548172757475
195    Dead Poets Society (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9163346613545817
196    Graduate, The (1967)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.104602510460251
197    Nikita (La Femme Nikita) (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0078740157480315
198    Bridge on the River Kwai, The (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.175757575757576
199    Shining, The (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.825242718446602
200    Evil Dead II (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5168539325842696
201    Groundhog Day (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7642857142857142
202    Unforgiven (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.868131868131868
203    Back to the Future (1985)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.834285714285714
204    Patton (1970)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9926470588235294
205    Akira (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.38
206    Cyrano de Bergerac (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8181818181818183
207    Young Frankenstein (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.945
208    This Is Spinal Tap (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.905759162303665
209    Indiana Jones and the Last Crusade (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.930513595166163
210    M*A*S*H (1970)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.912621359223301
211    Unbearable Lightness of Being, The (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4565217391304346
212    Room with a View, A (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.985074626865672
213    Pink Floyd - The Wall (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3508771929824563
214    Field of Dreams (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.69811320754717
215    When Harry Met Sally... (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.910344827586207
216    Bram Stoker's Dracula (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.158333333333333
217    Cape Fear (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.456140350877193
218    Nightmare on Elm Street, A (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.171171171171171
219    Mirror Has Two Faces, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3636363636363638
220    Breaking the Waves (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.72972972972973
221    Star Trek: First Contact (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.66027397260274
222    Sling Blade (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.198529411764706
223    Ridicule (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7045454545454546
224    101 Dalmatians (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.908256880733945
225    Die Hard 2 (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.355421686746988
226    Star Trek VI: The Undiscovered Country (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.279503105590062
227    Star Trek: The Wrath of Khan (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8155737704918034
228    Star Trek III: The Search for Spock (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.111111111111111
229    Star Trek IV: The Voyage Home (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4472361809045227
230    Batman Returns (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.683098591549296
231    Young Guns (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.207920792079208
232    Under Siege (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2903225806451615
233    Jaws (1975)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.775
234    Mars Attacks! (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.847926267281106
235    Citizen Ruth (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6222222222222222
236    Jerry Maguire (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7109375
237    Raising Arizona (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.875
238    Sneakers (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.513333333333333
239    Beavis and Butt-head Do America (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7884615384615383
240    Last of the Mohicans, The (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.546875
241    Kolya (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9914529914529915
242    Jungle2Jungle (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4393939393939394
243    Smilla's Sense of Snow (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
244    Devil's Own, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1083333333333334
245    Chasing Amy (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.935483870967742
246    Turbo: A Power Rangers Movie (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8
247    Grosse Pointe Blank (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.675
248    Austin Powers: International Man of Mystery (1...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.246153846153846
249    Fifth Element, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4771573604060912
250    Shall We Dance? (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.260869565217392
251    Lost World: Jurassic Park, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9430379746835444
252    Pillow Book, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6923076923076925
253    Batman & Robin (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4516129032258065
254    My Best Friend's Wedding (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.36046511627907
255    When the Cats Away (Chacun cherche son chat) (...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5625
256    Men in Black (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.745874587458746
257    Contact (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8035363457760316
258    George of the Jungle (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.685185185185185
259    Event Horizon (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.574803149606299
260    Air Bud (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.558139534883721
261    In the Company of Men (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.712121212121212
262    Steel (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1578947368421053
263    Mimic (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.742574257425743
264    Hunt for Red October, The (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8634361233480177
265    Kull the Conqueror (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7142857142857144
266    unknown
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4444444444444446
267    Chasing Amy (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.792156862745098
268    Full Monty, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.926984126984127
269    Gattaca (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5955882352941178
270    Starship Troopers (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2322274881516586
271    Good Will Hunting (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.262626262626263
272    Heat (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.569506726457399
273    Sabrina (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
274    Sense and Sensibility (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0111940298507465
275    Leaving Las Vegas (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.697986577181208
276    Restoration (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.464788732394366
277    Bed of Roses (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2333333333333334
278    Once Upon a Time... When We Were Colored (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
279    Up Close and Personal (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1882352941176473
280    River Wild, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.143835616438356
281    Time to Kill, A (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.685344827586207
282    Emma (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7175141242937855
283    Tin Cup (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.160621761658031
284    Secrets & Lies (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.265432098765432
285    English Patient, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.656964656964657
286    Marvin's Room (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.58974358974359
287    Scream (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4414225941422596
288    Evita (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9806949806949805
289    Fierce Creatures (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1145833333333335
290    Absolute Power (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.37007874015748
291    Rosewood (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
292    Donnie Brasco (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.802721088435374
293    Liar Liar (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.156701030927835
294    Breakdown (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4025974025974026
295    Promesse, La (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
296    Ulee's Gold (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.96
297    Face/Off (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.768041237113402
298    Hoodlum (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9315068493150687
299    Air Force One (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6310904872389793
300    In & Out (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3043478260869565
301    L.A. Confidential (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.161616161616162
302    Ulee's Gold (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6865671641791047
303    Fly Away Home (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5369127516778525
304    Ice Storm, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6436781609195403
305    Mrs. Brown (Her Majesty, Mrs. Brown) (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9479166666666665
306    Devil's Advocate, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.515957446808511
307    FairyTale: A True Story (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.966666666666667
308    Deceiver (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.857142857142857
309    Rainmaker, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6
310    Wings of the Dove, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.68
311    Midnight in the Garden of Good and Evil (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1625
312    Titanic (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.2457142857142856
313    3 Ninjas: High Noon At Mega Mountain (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
314    Apt Pupil (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1
315    As Good As It Gets (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.196428571428571
316    In the Name of the Father (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.911764705882353
317    Schindler's List (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.466442953020135
318    Everyone Says I Love You (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2738095238095237
319    Paradise Lost: The Child Murders at Robin Hood...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.05
320    Mother (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1301775147928996
321    Murder at 1600 (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0871559633027523
322    Dante's Peak (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.933333333333333
323    Lost Highway (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.136
324    Crash (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.546875
325    G.I. Jane (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.36
326    Cop Land (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3771428571428572
327    Conspiracy Theory (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4237288135593222
328    Desperate Measures (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
329    187 (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.024390243902439
330    Edge, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5398230088495577
331    Kiss the Girls (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4615384615384617
332    Game, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.593625498007968
333    U Turn (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.359375
334    How to Be a Player (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.761904761904762
335    Playing God (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.627906976744186
336    House of Yes, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
337    Bean (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.659340659340659
338    Mad City (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25531914893617
339    Boogie Nights (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5873015873015874
340    Critical Care (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.090909090909091
341    Man Who Knew Too Little, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.923076923076923
342    Alien: Resurrection (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.096774193548387
343    Apostle, The (1997)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6545454545454548
344    Deconstructing Harry (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
345    Jackie Brown (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.642857142857143
346    Wag the Dog (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.510948905109489
347    Desperate Measures (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2962962962962963
348    Hard Rain (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.903225806451613
349    Fallen (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1463414634146343
350    Prophecy II, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7
351    Spice World (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1153846153846154
352    Deep Rising (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
353    Wedding Singer, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.486111111111111
354    Sphere (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.926829268292683
355    Client, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.381443298969072
356    One Flew Over the Cuckoo's Nest (1975)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.291666666666667
357    Spawn (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6153846153846154
358    Assignment, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
359    Wonderland (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
360    Incognito (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
361    Blues Brothers 2000 (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8214285714285716
362    Sudden Death (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.723404255319149
363    Ace Ventura: When Nature Calls (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.675675675675676
364    Powder (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2083333333333335
365    Dangerous Minds (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3404255319148937
366    Clueless (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.458823529411765
367    Bio-Dome (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.903225806451613
368    Black Sheep (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6363636363636362
369    Mary Reilly (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8205128205128207
370    Bridges of Madison County, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1641791044776117
371    Jeffrey (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5294117647058822
372    Judge Dredd (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8974358974358974
373    Mighty Morphin Power Rangers: The Movie (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.272727272727273
374    Showgirls (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.9565217391304348
375    Houseguest (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8333333333333335
376    Heavyweights (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1538461538461537
377    Miracle on 34th Street (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.722772277227723
378    Tales From the Crypt Presents: Demon Knight (1...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9767441860465116
379    Star Trek: Generations (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.336206896551724
380    Muriel's Wedding (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.55
381    Adventures of Priscilla, Queen of the Desert, ...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5945945945945947
382    Flintstones, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.064516129032258
383    Naked Gun 33 1/3: The Final Insult (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.782608695652174
384    True Lies (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5625
385    Addams Family Values (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8160919540229883
386    Age of Innocence, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3846153846153846
387    Beverly Hills Cop III (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.392857142857143
388    Black Beauty (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4444444444444446
389    Fear of a Black Hat (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
390    Last Action Hero (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7457627118644066
391    Man Without a Face, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5441176470588234
392    Mrs. Doubtfire (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4114583333333335
393    Radioland Murders (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
394    Robin Hood: Men in Tights (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5892857142857144
395    Serial Mom (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.814814814814815
396    Striking Distance (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5833333333333335
397    Super Mario Bros. (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.076923076923077
398    Three Musketeers, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.303370786516854
399    Little Rascals, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7222222222222223
400    Brady Bunch Movie, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8026315789473686
401    Ghost (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4647058823529413
402    Batman (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.427860696517413
403    Pinocchio (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6732673267326734
404    Mission: Impossible (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.313953488372093
405    Thinner (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4489795918367347
406    Spy Hard (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.511627906976744
407    Close Shave, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.491071428571429
408    Jack (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.142857142857143
409    Kingpin (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1296296296296298
410    Nutty Professor, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.914110429447853
411    Very Brady Sequel, A (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3978494623655915
412    Tales from the Crypt Presents: Bordello of Blo...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6363636363636362
413    My Favorite Year (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.532258064516129
414    Apple Dumpling Gang, The (1975)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.84
415    Old Yeller (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.484375
416    Parent Trap, The (1961)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.095890410958904
417    Cinderella (1950)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5813953488372094
418    Mary Poppins (1964)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7247191011235956
419    Alice in Wonderland (1951)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
420    William Shakespeare's Romeo and Juliet (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5943396226415096
421    Aladdin and the King of Thieves (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8461538461538463
422    E.T. the Extra-Terrestrial (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8333333333333335
423    Children of the Corn: The Gathering (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.3157894736842106
424    Bob Roberts (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7411764705882353
425    Transformers: The Movie, The (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.84375
426    To Kill a Mockingbird (1962)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.292237442922374
427    Harold and Maude (1971)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8181818181818183
428    Day the Earth Stood Still, The (1951)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9381443298969074
429    Duck Soup (1933)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
430    Highlander (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5359477124183005
431    Fantasia (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7701149425287355
432    Heathers (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.690058479532164
433    Forbidden Planet (1956)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8358208955223883
434    Butch Cassidy and the Sundance Kid (1969)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.949074074074074
435    American Werewolf in London, An (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5353535353535355
436    Amityville 1992: It's About Time (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
437    Amityville 3-D (1983)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.1666666666666667
438    Amityville: A New Generation (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
439    Amityville II: The Possession (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6428571428571428
440    Amityville Horror, The (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5660377358490565
441    Amityville Curse, The (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.25
442    Birds, The (1963)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.808641975308642
443    Blob, The (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.717391304347826
444    Body Snatcher, The (1945)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
445    Burnt Offerings (1976)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4444444444444446
446    Carrie (1976)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5041322314049586
447    Omen, The (1976)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.388235294117647
448    Star Trek: The Motion Picture (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.034188034188034
449    Star Trek V: The Final Frontier (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3968253968253967
450    Grease (1978)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.347058823529412
451    Jaws 2 (1978)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
452    Jaws 3-D (1983)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.9375
453    Bastard Out of Carolina (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.875
454    Jackie Chan's First Strike (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2551724137931033
455    Beverly Hills Ninja (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3125
456    Free Willy 3: The Rescue (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.7407407407407407
457    Nixon (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1222222222222222
458    Cry, the Beloved Country (1995)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
459    Crossing Guard, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
460    Smoke (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6216216216216215
461    Like Water For Chocolate (Como agua para choco...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.804054054054054
462    Secret of Roan Inish, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.859154929577465
463    Vanya on 42nd Street (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5925925925925926
464    Jungle Book, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5647058823529414
465    Red Rock West (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5961538461538463
466    Bronx Tale, A (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7916666666666665
467    Rudy (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3125
468    Short Cuts (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7761194029850746
469    Tombstone (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
470    Courage Under Fire (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6108597285067874
471    Dragonheart (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0822784810126582
472    James and the Giant Peach (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.126984126984127
473    Dr. Strangelove or: How I Learned to Stop Worr...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.252577319587629
474    Trainspotting (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.884
475    First Wives Club, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.01875
476    Matilda (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.210526315789474
477    Philadelphia Story, The (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.115384615384615
478    Vertigo (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.251396648044692
479    North by Northwest (1959)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.284916201117318
480    Apartment, The (1960)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9365079365079363
481    Some Like It Hot (1959)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.984375
482    Casablanca (1942)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.45679012345679
483    Maltese Falcon, The (1941)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.2101449275362315
484    My Fair Lady (1964)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.816
485    Sabrina (1954)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.796875
486    Roman Holiday (1953)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.102941176470588
487    Sunset Blvd. (1950)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.2
488    Notorious (1946)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.115384615384615
489    To Catch a Thief (1955)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.02
490    Adventures of Robin Hood, The (1938)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.791044776119403
491    East of Eden (1955)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.864406779661017
492    Thin Man, The (1934)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.15
493    His Girl Friday (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
494    Around the World in 80 Days (1956)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6610169491525424
495    It's a Wonderful Life (1946)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.121212121212121
496    Bringing Up Baby (1938)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.838235294117647
497    African Queen, The (1951)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.184210526315789
498    Cat on a Hot Tin Roof (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9516129032258065
499    Fly Away Home (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.903225806451613
500    Dumbo (1941)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4959349593495936
501    Bananas (1971)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7017543859649122
502    Candidate, The (1972)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.641025641025641
503    Bonnie and Clyde (1967)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.819672131147541
504    Dial M for Murder (1954)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
505    Rebel Without a Cause (1955)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8555555555555556
506    Streetcar Named Desire, A (1951)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.816326530612245
507    People vs. Larry Flynt, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5953488372093023
508    My Left Foot (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8512396694214877
509    Magnificent Seven, The (1954)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9421487603305785
510    Lawrence of Arabia (1962)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.23121387283237
511    Wings of Desire (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
512    Third Man, The (1949)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.333333333333333
513    Annie Hall (1977)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.911111111111111
514    Boot, Das (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.203980099502488
515    Local Hero (1983)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9682539682539684
516    Manhattan (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.769230769230769
517    Miller's Crossing (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.651685393258427
518    Treasure of the Sierra Madre, The (1948)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1
519    Great Escape, The (1963)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.104838709677419
520    Deer Hunter, The (1978)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8333333333333335
521    Down by Law (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7714285714285714
522    Cool Hand Luke (1967)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9939024390243905
523    Great Dictator, The (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.021739130434782
524    Big Sleep, The (1946)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.027397260273973
525    Ben-Hur (1959)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8306451612903225
526    Gandhi (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.02051282051282
527    Killing Fields, The (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.132231404958677
528    My Life as a Dog (Mitt liv som hund) (1985)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.978494623655914
529    Man Who Would Be King, The (1975)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.025
530    Shine (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9224806201550386
531    Kama Sutra: A Tale of Love (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3181818181818183
532    Daytrippers, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
533    Traveller (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3076923076923075
534    Addicted to Love (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
535    Ponette (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3
536    My Own Private Idaho (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6333333333333333
537    Anastasia (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4242424242424243
538    Mouse Hunt (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.477272727272727
539    Money Train (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.511627906976744
540    Mortal Kombat (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.877551020408163
541    Pocahontas (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5294117647058822
542    Misérables, Les (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.619047619047619
543    Things to Do in Denver when You're Dead (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1549295774647885
544    Vampire in Brooklyn (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8333333333333333
545    Broken Arrow (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.031496062992126
546    Young Poisoner's Handbook, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.341463414634146
547    NeverEnding Story III, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1666666666666665
548    Rob Roy (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5652173913043477
549    Die Hard: With a Vengeance (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2847682119205297
550    Lord of Illusions (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4166666666666665
551    Species (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8666666666666667
552    Walk in the Clouds, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
553    Waterworld (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.803921568627451
554    White Man's Burden (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
555    Wild Bill (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
556    Farinelli: il castrato (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1176470588235294
557    Heavenly Creatures (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6714285714285713
558    Interview with the Vampire (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1824817518248176
559    Kid in King Arthur's Court, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.727272727272727
560    Mary Shelley's Frankenstein (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0677966101694913

561    Quick and the Dead, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2083333333333335
562    Stephen King's The Langoliers (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.413793103448276
563    Tales from the Hood (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.037037037037037
564    Village of the Damned (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6818181818181817
565    Clear and Present Danger (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.569832402234637
566    Wes Craven's New Nightmare (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
567    Speed (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6478260869565218
568    Wolf (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.701492537313433
569    Wyatt Earp (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1
570    Another Stakeout (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
571    Blown Away (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7586206896551726
572    Body Snatchers (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9393939393939394
573    Boxing Helena (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2
574    City Slickers II: The Legend of Curly's Gold (...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5454545454545454
575    Cliffhanger (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.021505376344086
576    Coneheads (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2195121951219514
577    Demolition Man (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.152173913043478
578    Fatal Instinct (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6315789473684212
579    Englishman Who Went Up a Hill, But Came Down a...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.375
580    Kalifornia (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2203389830508473
581    Piano, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6011904761904763
582    Romeo Is Bleeding (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
583    Secret Garden, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5443037974683542
584    Son in Law (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4871794871794872
585    Terminal Velocity (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.676470588235294
586    Hour of the Pig, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5714285714285716
587    Beauty and the Beast (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.792079207920792
588    Wild Bunch, The (1969)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.023255813953488
589    Hellraiser: Bloodline (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
590    Primal Fear (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.601123595505618
591    True Crime (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
592    Stalingrad (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
593    Heavy (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
594    Fan, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.09375
595    Hunchback of Notre Dame, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.377952755905512
596    Eraser (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.150485436893204
597    Big Squeeze, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
598    Police Story 4: Project S (Chao ji ji hua) (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
599    Daniel Defoe's Robinson Crusoe (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
600    For Whom the Bell Tolls (1943)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
601    American in Paris, An (1951)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7
602    Rear Window (1954)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.3875598086124405
603    It Happened One Night (1934)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.012345679012346
604    Meet Me in St. Louis (1944)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3548387096774195
605    All About Eve (1950)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.045454545454546
606    Rebecca (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9696969696969697
607    Spellbound (1945)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.933333333333333
608    Father of the Bride (1950)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5833333333333335
609    Gigi (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.658536585365854
610    Laura (1944)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1
611    Lost Horizon (1937)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9411764705882355
612    My Man Godfrey (1936)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.037037037037037
613    Giant (1956)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7450980392156863
614    39 Steps, The (1935)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0508474576271185
615    Night of the Living Dead (1968)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.421875
616    Blue Angel, The (Blaue Engel, Der) (1930)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7777777777777777
617    Picnic (1955)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.611111111111111
618    Extreme Measures (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.171875
619    Chamber, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0930232558139537
620    Davy Crockett, King of the Wild Frontier (1955)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.909090909090909
621    Swiss Family Robinson (1960)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.358974358974359
622    Angels in the Outfield (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.923076923076923
623    Three Caballeros, The (1945)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.272727272727273
624    Sword in the Stone, The (1963)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3292682926829267
625    So Dear to My Heart (1949)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
626    Robin Hood: Prince of Thieves (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2266666666666666
627    Sleepers (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.514792899408284
628    Victor/Victoria (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3376623376623376
629    Great Race, The (1965)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2903225806451615
630    Crying Game, The (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6218487394957983
631    Sophie's Choice (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.896551724137931
632    Christmas Carol, A (1938)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.057971014492754
633    Microcosmos: Le peuple de l'herbe (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
634    Fog, The (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.739130434782609
635    Escape from New York (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.241758241758242
636    Howling, The (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.026315789473684
637    Return of Martin Guerre, The (Retour de Martin...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.772727272727273
638    Tin Drum, The (Blechtrommel, Die) (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7
639    Cook the Thief His Wife & Her Lover, The (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.024390243902439
640    Paths of Glory (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.212121212121212
641    Grifters, The (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4831460674157304
642    The Innocent (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
643    Thin Blue Line, The (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7714285714285714
644    Paris Is Burning (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.814814814814815
645    Once Upon a Time in the West (1969)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8684210526315788
646    Ran (1985)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1
647    Quiet Man, The (1952)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.029850746268656
648    Once Upon a Time in America (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
649    Seventh Seal, The (Sjunde inseglet, Det) (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5416666666666665
650    Glory (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.076023391812866
651    Rosencrantz and Guildenstern Are Dead (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.888888888888889
652    Touch of Evil (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.911764705882353
653    Chinatown (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.136054421768708
654    Stand by Me (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.881057268722467
655    M (1931)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
656    Manchurian Candidate, The (1962)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.259541984732825
657    Pump Up the Volume (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4177215189873418
658    Arsenic and Old Lace (1944)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.078260869565217
659    Fried Green Tomatoes (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.764705882352941
660    High Noon (1952)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1022727272727275
661    Somewhere in Time (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.426829268292683
662    Being There (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9051724137931036
663    Paris, Texas (1984)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5434782608695654
664    Alien 3 (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.83
665    Blood For Dracula (Andy Warhol's Dracula) (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
666    Audrey Rose (1977)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1666666666666665
667    Blood Beach (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1666666666666665
668    Body Parts (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6153846153846154
669    Body Snatchers (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
670    Bride of Frankenstein (1935)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.608695652173913
671    Candyman (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.723076923076923
672    Cape Fear (1962)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5232558139534884
673    Cat People (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8958333333333335
674    Nosferatu (Nosferatu, eine Symphonie des Graue...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5555555555555554
675    Crucible, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3376623376623376
676    Fire on the Mountain (1996)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
677    Volcano (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.808219178082192
678    Conan the Barbarian (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.046728971962617
679    Kull the Conqueror (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5588235294117645
680    Wishmaster (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4444444444444446
681    I Know What You Did Last Summer (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.06
682    Rocket Man (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4081632653061225
683    In the Line of Fire (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7928994082840237
684    Executive Decision (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.356687898089172
685    Perfect World, A (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.68
686    McHale's Navy (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1884057971014492
687    Leave It to Beaver (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8409090909090908
688    Jackal, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1494252873563218
689    Seven Years in Tibet (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.458064516129032
690    Dark City (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
691    American President, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6280487804878048
692    Casino (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6483516483516483
693    Persuasion (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.045454545454546
694    Kicking and Screaming (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.923076923076923
695    City Hall (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1392405063291138
696    Basketball Diaries, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.425
697    Browning Version, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
698    Little Women (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.676470588235294
699    Miami Rhapsody (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
700    Wonderful, Horrible Life of Leni Riefenstahl, ...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
701    Barcelona (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.018867924528302
702    Widows' Peak (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5789473684210527
703    House of the Spirits, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0416666666666665
704    Singin' in the Rain (1952)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9927007299270074
705    Bad Moon (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
706    Enchanted April (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9285714285714284
707    Sex, Lies, and Videotape (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4752475247524752
708    Strictly Ballroom (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.028846153846154
709    Better Off Dead... (1985)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.569620253164557
710    Substance of Fire, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
711    Tin Men (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0784313725490198
712    Othello (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.611111111111111
713    Carrington (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.230769230769231
714    To Die For (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2758620689655173
715    Home for the Holidays (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1551724137931036
716    Juror, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.817073170731707
717    In the Bleak Midwinter (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6875
718    Canadian Bacon (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.413793103448276
719    First Knight (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0232558139534884
720    Mallrats (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4444444444444446
721    Nine Months (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9310344827586206
722    Boys on the Side (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1470588235294117
723    Circle of Friends (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.486842105263158
724    Exit to Eden (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
725    Fluke (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
726    Immortal Beloved (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4603174603174605
727    Junior (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.022222222222222
728    Nell (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4814814814814814
729    Queen Margot (Reine Margot, La) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
730    Corrina, Corrina (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1538461538461537
731    Dave (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.65
732    Go Fish (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
733    Made in America (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5185185185185186
734    Philadelphia (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.854014598540146
735    Shadowlands (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9358974358974357
736    Sirens (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.983050847457627
737    Threesome (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.838709677419355
738    Pretty Woman (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.323170731707317
739    Jane Eyre (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4761904761904763
740    Last Supper, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4482758620689653
741    Ransom (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.644194756554307
742    Crow: City of Angels, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.9487179487179487
743    Michael Collins (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4565217391304346
744    Ruling Class, The (1972)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.875
745    Real Genius (1985)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6638655462184873
746    Benny & Joon (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4607843137254903
747    Saint, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1234177215189876
748    MatchMaker, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.176470588235294
749    Amistad (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8548387096774195
750    Tomorrow Never Dies (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4277777777777776
751    Replacement Killers, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3076923076923075
752    Burnt By the Sun (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7083333333333335
753    Red Corner (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3859649122807016
754    Jumanji (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3125
755    Father of the Bride Part II (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8984375
756    Across the Sea of Time (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
757    Lawnmower Man 2: Beyond Cyberspace (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.7142857142857142
758    Fair Game (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1818181818181817
759    Screamers (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.652173913043478
760    Nick of Time (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0454545454545454
761    Beautiful Girls (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.391304347826087
762    Happy Gilmore (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.389261744966443
763    If Lucy Fell (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7586206896551726
764    Boomerang (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8125
765    Man of the Year (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.111111111111111
766    Addiction, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1818181818181817
767    Casper (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.076923076923077
768    Congo (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4523809523809526
769    Devil in a Blue Dress (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3859649122807016
770    Johnny Mnemonic (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6341463414634148
771    Kids (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.061224489795918
772    Mute Witness (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9411764705882355
773    Prophecy, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9375
774    Something to Talk About (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.769230769230769
775    Three Wishes (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2222222222222223
776    Castle Freak (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.25
777    Don Juan DeMarco (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5526315789473686
778    Drop Zone (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5483870967741935
779    Dumb & Dumber (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
780    French Kiss (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
781    Little Odessa (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
782    Milk Money (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.72972972972973
783    Beyond Bedlam (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
784    Only You (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1538461538461537
785    Perez Family, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.642857142857143
786    Roommates (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.230769230769231
787    Relative Fear (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6666666666666667
788    Swimming with Sharks (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.574468085106383
789    Tommy Boy (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.909090909090909
790    Baby-Sitters Club, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
791    Bullets Over Broadway (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7209302325581395
792    Crooklyn (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
793    It Could Happen to You (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.652173913043478
794    Richie Rich (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
795    Speechless (1994)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0833333333333335
796    Timecop (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.096774193548387
797    Bad Company (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2222222222222223
798    Boys Life (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
799    In the Mouth of Madness (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8846153846153846
800    Air Up There, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8125
801    Hard Target (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7
802    Heaven & Earth (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5555555555555554
803    Jimmy Hollywood (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.875
804    Manhattan Murder Mystery (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6296296296296298
805    Menace II Society (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.46
806    Poetic Justice (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7777777777777777
807    Program, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.838709677419355
808    Rising Sun (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9069767441860463
809    Shadow, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.888888888888889
810    Thirty-Two Short Films About Glenn Gould (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9444444444444446
811    Andre (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.111111111111111
812    Celluloid Closet, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.892857142857143
813    Great Day in Harlem, A (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
814    One Fine Day (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.232142857142857
815    Candyman: Farewell to the Flesh (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
816    Frisk (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
817    Girl 6 (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.76
818    Eddie (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7
819    Space Jam (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.774193548387097
820    Mrs. Winterbourne (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0454545454545454
821    Faces (1968)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
822    Mulholland Falls (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8780487804878048
823    Great White Hype, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7551020408163267
824    Arrival, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.036144578313253
825    Phantom, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.575
826    Daylight (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7719298245614037
827    Alaska (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6923076923076925
828    Fled (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6470588235294117
829    Power 98 (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
830    Escape from L.A. (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4615384615384617
831    Bogus (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5454545454545454
832    Bulletproof (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.204081632653061
833    Halloween: The Curse of Michael Myers (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2
834    Gay Divorcee, The (1934)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8666666666666667
835    Ninotchka (1939)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.769230769230769
836    Meet John Doe (1941)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.92
837    In the Line of Duty 2 (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
838    Loch Ness (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
839    Last Man Standing (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.660377358490566
840    Glimmer Man, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
841    Pollyanna (1960)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1481481481481484
842    Shaggy Dog, The (1959)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
843    Freeway (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.357142857142857
844    That Thing You Do! (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.465909090909091
845    To Gillian on Her 37th Birthday (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0681818181818183
846    Looking for Richard (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.727272727272727
847    Murder, My Sweet (1944)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5555555555555554
848    Days of Thunder (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7169811320754715
849    Perfect Candidate, A (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
850    Two or Three Things I Know About Her (1966)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
851    Bloody Child, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
852    Braindead (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.857142857142857
853    Bad Taste (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.375
854    Diva (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.727272727272727
855    Night on Earth (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8333333333333335
856    Paris Was a Woman (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
857    Amityville: Dollhouse (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
858    April Fool's Day (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
859    Believers, The (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
860    Nosferatu a Venezia (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
861    Jingle All the Way (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.111111111111111
862    Garden of Finzi-Contini, The (Giardino dei Fin...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9166666666666665
863    My Fellow Americans (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1627906976744184
864    Ice Storm, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4761904761904763
865    Michael (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.319327731092437
866    Whole Wide World, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
867    Hearts and Minds (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8
868    Fools Rush In (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
869    Touch (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7777777777777777
870    Vegas Vacation (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
871    Love Jones (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0952380952380953
872    Picture Perfect (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.962962962962963
873    Career Girls (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2564102564102564
874    She's So Lovely (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7358490566037736
875    Money Talks (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.702127659574468
876    Excess Baggage (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5384615384615383
877    That Darn Cat! (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.515151515151515
878    Peacemaker, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2720588235294117
879    Soul Food (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.169491525423729
880    Money Talks (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.933333333333333
881    Washington Square (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2941176470588234
882    Telling Lies in America (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.230769230769231
883    Year of the Horse (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
884    Phantoms (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.230769230769231
885    Life Less Ordinary, A (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0754716981132075
886    Eve's Bayou (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.609375
887    One Night Stand (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.466666666666667
888    Tango Lesson, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3846153846153846
889    Mortal Kombat: Annihilation (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.9534883720930232
890    Bent (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
891    Flubber (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7547169811320753
892    For Richer or Poorer (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
893    Home Alone 3 (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.894736842105263
894    Scream 2 (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2169811320754715
895    Sweet Hereafter, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.772727272727273
896    Time Tracers (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
897    Postman, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2241379310344827
898    Winter Guest, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4444444444444446
899    Kundun (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6904761904761907
900    Mr. Magoo (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.9166666666666667
901    Big Lebowski, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8333333333333335
902    Afterglow (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.111111111111111
903    Ma vie en rose (My Life in Pink) (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.45
904    Great Expectations (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2222222222222223
905    Oscar & Lucinda (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1904761904761907
906    Vermin (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
907    Half Baked (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
908    Dangerous Beauty (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.769230769230769

909    Nil By Mouth (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
910    Twilight (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
911    U.S. Marshalls (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
912    Love and Death on Long Island (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
913    Wild Things (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.727272727272727
914    Primary Colors (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.923076923076923
915    Lost in Space (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
916    Mercury Rising (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4285714285714284
917    City of Angels (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
918    City of Lost Children, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7916666666666665
919    Two Bits (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2
920    Farewell My Concubine (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9782608695652173
921    Dead Man (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.823529411764706
922    Raise the Red Lantern (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.155172413793103
923    White Squall (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
924    Unforgettable (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.323529411764706
925    Down Periscope (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.702970297029703
926    Flower of My Secret, The (Flor de mi secreto, ...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
927    Craft, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1153846153846154
928    Harriet the Spy (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7
929    Chain Reaction (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7
930    Island of Dr. Moreau, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1578947368421053
931    First Kid (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.925
932    Funeral, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
933    Preacher's Wife, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.926470588235294
934    Paradise Road (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
935    Brassed Off (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9375
936    Thousand Acres, A (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4054054054054053
937    Smile Like Yours, A (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.88
938    Murder in the First (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6
939    Airheads (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.34375
940    With Honors (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0652173913043477
941    What's Love Got to Do with It (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.488888888888889
942    Killing Zoe (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.475
943    Renaissance Man (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
944    Charade (1963)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.925
945    Fox and the Hound, The (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1475409836065573
946    Big Blue, The (Grand bleu, Le) (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.235294117647059
947    Booty Call (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1666666666666665
948    How to Make an American Quilt (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3380281690140845
949    Georgia (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9
950    Indian in the Cupboard, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8205128205128207
951    Blue in the Face (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1777777777777776
952    Unstrung Heroes (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3181818181818183
953    Unzipped (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5454545454545454
954    Before Sunrise (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4081632653061225
955    Nobody's Fool (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.608695652173913
956    Pushing Hands (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
957    To Live (Huozhe) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7857142857142856
958    Dazed and Confused (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.46875
959    Naked (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.24
960    Orlando (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6176470588235294
961    Ruby in Paradise (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.130434782608696
962    Some Folks Call It a Sling Blade (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.2926829268292686
963    Month by the Lake, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
964    Funny Face (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
965    Affair to Remember, An (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1923076923076925
966    Little Lord Fauntleroy (1936)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
967    Inspector General, The (1949)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7222222222222223
968    Winnie the Pooh and the Blustery Day (1968)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8
969    Hear My Song (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
970    Mediterraneo (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.676470588235294
971    Passion Fish (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1785714285714284
972    Grateful Dead (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
973    Eye for an Eye (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.03125
974    Fear (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.159090909090909
975    Solo (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8333333333333333
976    Substitute, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.693877551020408
977    Heaven's Prisoners (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5185185185185186
978    Trigger Effect, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
979    Mother Night (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1818181818181817
980    Dangerous Ground (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.75
981    Maximum Risk (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
982    Rich Man's Wife, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
983    Shadow Conspiracy (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8636363636363638
984    Blood & Wine (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8636363636363638
985    Turbulence (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5652173913043477
986    Underworld (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
987    Beautician and the Beast, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.313953488372093
988    Cats Don't Dance (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.84375
989    Anna Karenina (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.090909090909091
990    Keys to Tulsa (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.24
991    Head Above Water (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
992    Hercules (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.515151515151515
993    Last Time I Committed Suicide, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2857142857142856
994    Kiss Me, Guido (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.161290322580645
995    Big Green, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
996    Stuart Saves His Family (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.125
997    Cabin Boy (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5625
998    Clean Slate (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
999    Lightning Jack (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1000    Stupids, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1001    Pest, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.875
1002    That Darn Cat! (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1003    Geronimo: An American Legend (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.111111111111111
1004    Double vie de Véronique, La (Double Life of Ve...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6818181818181817
1005    Until the End of the World (Bis ans Ende der W...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8260869565217392
1006    Waiting for Guffman (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.127659574468085
1007    I Shot Andy Warhol (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3783783783783785
1008    Stealing Beauty (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.375
1009    Basquiat (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1010    2 Days in the Valley (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.225806451612903
1011    Private Parts (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.53
1012    Anaconda (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.289473684210526
1013    Romy and Michele's High School Reunion (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.061224489795918
1014    Shiloh (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8333333333333335
1015    Con Air (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.45985401459854
1016    Trees Lounge (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.24
1017    Tie Me Up! Tie Me Down! (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1875
1018    Die xue shuang xiong (Killer, The) (1989)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.967741935483871
1019    Gaslight (1944)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8857142857142857
1020    8 1/2 (1963)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8157894736842106
1021    Fast, Cheap & Out of Control (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4375
1022    Fathers' Day (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5806451612903225
1023    Mrs. Dalloway (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6
1024    Fire Down Below (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9318181818181817
1025    Lay of the Land, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1026    Shooter, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1027    Grumpier Old Men (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0405405405405403
1028    Jury Duty (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1029    Beverly Hillbillies, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1030    Lassie (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2857142857142856
1031    Little Big League (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.875
1032    Homeward Bound II: Lost in San Francisco (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.78125
1033    Quest, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5185185185185186
1034    Cool Runnings (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.161764705882353
1035    Drop Dead Fred (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1036    Grease 2 (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1037    Switchback (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.823529411764706
1038    Hamlet (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.011111111111111
1039    Two if by Sea (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
1040    Forget Paris (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.193548387096774
1041    Just Cause (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.142857142857143
1042    Rent-a-Kid (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1043    Paper, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.225
1044    Fearless (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.24
1045    Malice (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1739130434782608
1046    Multiplicity (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8358208955223883
1047    She's the One (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0136986301369864
1048    House Arrest (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.52
1049    Ghost and Mrs. Muir, The (1947)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6511627906976742
1050    Associate, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2439024390243905
1051    Dracula: Dead and Loving It (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.28
1052    Now and Then (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4583333333333335
1053    Mr. Wrong (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3043478260869565
1054    Simple Twist of Fate, A (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
1055    Cronos (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
1056    Pallbearer, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3181818181818183
1057    War, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2666666666666666
1058    Don't Be a Menace to South Central While Drink...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7714285714285714
1059    Adventures of Pinocchio, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.051282051282051
1060    Evening Star, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9310344827586206
1061    Four Days in September (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
1062    Little Princess, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.658536585365854
1063    Crossfire (1947)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.25
1064    Koyaanisqatsi (1983)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.490566037735849
1065    Balto (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1066    Bottle Rocket (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4545454545454546
1067    Star Maker, The (Uomo delle stelle, L') (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
1068    Amateur (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
1069    Living in Oblivion (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.740740740740741
1070    Party Girl (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.875
1071    Pyromaniac's Love Story, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1072    Shallow Grave (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8181818181818183
1073    Reality Bites (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.961038961038961
1074    Man of No Importance, A (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4285714285714284
1075    Pagemaster, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1076    Love and a .45 (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.125
1077    Oliver & Company (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.772727272727273
1078    Joe's Apartment (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2444444444444445
1079    Celestial Clockwork (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1080    Curdled (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1081    Female Perversions (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.625
1082    Albino Alligator (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1083    Anne Frank Remembered (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.857142857142857
1084    Carried Away (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1085    It's My Party (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
1086    Bloodsport 2 (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.7
1087    Double Team (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.230769230769231
1088    Speed 2: Cruise Control (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1315789473684212
1089    Sliver (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4054054054054053
1090    Pete's Dragon (1977)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7209302325581395
1091    Dear God (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1092    Live Nude Girls (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0869565217391304
1093    Thin Line Between Love and Hate, A (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4166666666666665
1094    High School High (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6206896551724137
1095    Commandments (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1096    Hate (Haine, La) (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1097    Flirting With Disaster (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6904761904761907
1098    Red Firecracker, Green Firecracker (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4615384615384617
1099    What Happened Was... (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.625
1100    Six Degrees of Separation (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.77027027027027
1101    Two Much (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1102    Trust (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.789473684210526
1103    C'est arrivé près de chez vous (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1104    Firestorm (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8333333333333335
1105    Newton Boys, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1106    Beyond Rangoon (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0555555555555554
1107    Feast of July (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
1108    Death and the Maiden (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4285714285714284
1109    Tank Girl (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8536585365853657
1110    Double Happiness (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4285714285714284
1111    Cobb (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1112    Mrs. Parker and the Vicious Circle (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.272727272727273
1113    Faithful (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3
1114    Twelfth Night (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.413793103448276
1115    Mark of Zorro, The (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6153846153846154
1116    Surviving Picasso (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1052631578947367
1117    Up in Smoke (1978)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25531914893617
1118    Some Kind of Wonderful (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6610169491525424
1119    I'm Not Rappaport (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1120    Umbrellas of Cherbourg, The (Parapluies de Che...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.761904761904762
1121    They Made Me a Criminal (1939)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1122    Last Time I Saw Paris, The (1954)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1123    Farewell to Arms, A (1932)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8333333333333335
1124    Innocents, The (1961)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.25
1125    Old Man and the Sea, The (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.34375
1126    Truman Show, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.909090909090909
1127    Heidi Fleiss: Hollywood Madam (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6923076923076925
1128    Chungking Express (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5714285714285716
1129    Jupiter's Wife (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1130    Safe (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1131    Feeling Minnesota (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.625
1132    Escape to Witch Mountain (1975)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.966666666666667
1133    Get on the Bus (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3157894736842106
1134    Doors, The (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9782608695652173
1135    Ghosts of Mississippi (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4827586206896552
1136    Beautiful Thing (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9655172413793105
1137    Best Men (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
1138    Hackers (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.606060606060606
1139    Road to Wellville, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2941176470588234
1140    War Room, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335

1141    When We Were Kings (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.045454545454546
1142    Hard Eight (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1143    Quiet Room, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1144    Blue Chips (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1145    Calendar Girl (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1146    My Family (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1147    Tom & Viv (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1148    Walkabout (1971)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8461538461538463
1149    Last Dance (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.111111111111111
1150    Original Gangstas (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.142857142857143
1151    In Love and War (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4285714285714284
1152    Backbeat (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.473684210526316
1153    Alphaville (1965)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1154    Rendezvous in Paris (Rendez-vous de Paris, Les...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1155    Cyclo (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1156    Relic, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.88
1157    Fille seule, La (A Single Girl) (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1158    Stalker (1979)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5454545454545454
1159    Love! Valour! Compassion! (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6153846153846154
1160    Palookaville (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.923076923076923
1161    Phat Beach (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6
1162    Portrait of a Lady, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.68
1163    Zeus and Roxanne (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1666666666666665
1164    Big Bully (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8571428571428572
1165    Love & Human Remains (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
1166    Sum of Us, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5454545454545454
1167    Little Buddha (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3181818181818183
1168    Fresh (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.1
1169    Spanking the Monkey (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.074074074074074
1170    Wild Reeds (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.142857142857143
1171    Women, The (1939)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1172    Bliss (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5714285714285716
1173    Caught (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1174    Hugo Pool (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
1175    Welcome To Sarajevo (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3636363636363638
1176    Dunston Checks In (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8571428571428572
1177    Major Payne (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.473684210526316
1178    Man of the House (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.111111111111111
1179    I Love Trouble (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1180    Low Down Dirty Shame, A (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1181    Cops and Robbersons (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3076923076923075
1182    Cowboy Way, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.210526315789474
1183    Endless Summer 2, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1184    In the Army Now (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2777777777777777
1185    Inkwell, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1186    Switchblade Sisters (1975)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.230769230769231
1187    Young Guns II (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.772727272727273
1188    Prefontaine (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1189    That Old Feeling (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3636363636363638
1190    Letter From Death Row, A (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.333333333333333
1191    Boys of St. Vincent, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3846153846153846
1192    Before the Rain (Pred dozhdot) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8
1193    Once Were Warriors (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.064516129032258
1194    Strawberry and Chocolate (Fresa y chocolate) (...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.272727272727273
1195    Savage Nights (Nuits fauves, Les) (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1196    Family Thing, A (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5555555555555554
1197    Purple Noon (1960)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.142857142857143
1198    Cemetery Man (Dellamorte Dellamore) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.869565217391304
1199    Kim (1950)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
1200    Marlene Dietrich: Shadow and Light (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1201    Maybe, Maybe Not (Bewegte Mann, Der) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1202    Top Hat (1935)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0476190476190474
1203    To Be or Not to Be (1942)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.611111111111111
1204    Secret Agent, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1205    Amos & Andrew (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6842105263157894
1206    Jade (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2941176470588234
1207    Kiss of Death (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.85
1208    Mixed Nuts (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.533333333333333
1209    Virtuosity (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.736842105263158
1210    Blue Sky (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4166666666666665
1211    Flesh and Bone (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8333333333333335
1212    Guilty as Sin (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1666666666666665
1213    In the Realm of the Senses (Ai no corrida) (1976)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1214    Barb Wire (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.9333333333333333
1215    Kissed (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1216    Assassins (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.871794871794872
1217    Friday (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4615384615384617
1218    Goofy Movie, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9
1219    Higher Learning (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1220    When a Man Loves a Woman (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4871794871794872
1221    Judgment Night (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.68
1222    King of the Hill (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1223    Scout, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1224    Angus (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.642857142857143
1225    Night Falls on Manhattan (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.375
1226    Awfully Big Adventure, An (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.375
1227    Under Siege 2: Dark Territory (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4583333333333335
1228    Poison Ivy II (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1538461538461537
1229    Ready to Wear (Pret-A-Porter) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8333333333333333
1230    Marked for Death (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1231    Madonna: Truth or Dare (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4705882352941178
1232    Nénette et Boni (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1233    Chairman of the Board (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.375
1234    Big Bang Theory, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1235    Other Voices, Other Rooms (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1236    Twisted (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1237    Full Speed (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.125
1238    Cutthroat Island (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4444444444444446
1239    Ghost in the Shell (Kokaku kidotai) (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6538461538461537
1240    Van, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1241    Old Lady Who Walked in the Sea, The (Vieille q...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
1242    Night Flier (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7142857142857144
1243    Metro (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.9166666666666665
1244    Gridlock'd (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.210526315789474
1245    Bushwhacked (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5714285714285714
1246    Bad Girls (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8333333333333333
1247    Blink (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1248    For Love or Money (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8333333333333335
1249    Best of the Best 3: No Turning Back (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1250    A Chef in Love (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.125

1251    Contempt (Mépris, Le) (1963)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1252    Tie That Binds, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1253    Gone Fishin' (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8181818181818181
1254    Broken English (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1255    Designated Mourner, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1256    Designated Mourner, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.75
1257    Trial and Error (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5217391304347827
1258    Pie in the Sky (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1259    Total Eclipse (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1260    Run of the Country, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1261    Walking and Talking (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.625
1262    Foxfire (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.933333333333333
1263    Nothing to Lose (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
1264    Star Maps (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0526315789473686
1265    Bread and Chocolate (Pane e cioccolata) (1973)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
1266    Clockers (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1267    Bitter Moon (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3
1268    Love in the Afternoon (1957)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.9
1269    Life with Mikey (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2857142857142856
1270    North (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7142857142857144
1271    Talking About Sex (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8
1272    Color of Night (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7333333333333334
1273    Robocop 3 (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.7272727272727273
1274    Killer (Bulletproof Heart) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1275    Sunset Park (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1276    Set It Off (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4210526315789473
1277    Selena (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.625
1278    Wild America (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.888888888888889
1279    Gang Related (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6875
1280    Manny & Lo (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1538461538461537
1281    Grass Harp, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2222222222222223
1282    Out to Sea (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6842105263157894
1283    Before and After (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8461538461538463
1284    Princess Caraboo (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1333333333333333
1285    Shall We Dance? (1937)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7058823529411766
1286    Ed (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.3333333333333333
1287    Denise Calls Up (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1288    Jack and Sarah (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.142857142857143
1289    Country Life (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1290    Celtic Pride (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2
1291    Simple Wish, A (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6666666666666667
1292    Star Kid (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1293    Ayn Rand: A Sense of Life (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.142857142857143
1294    Kicked in the Head (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5714285714285716
1295    Indian Summer (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1296    Love Affair (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8333333333333335
1297    Band Wagon, The (1953)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1298    Penny Serenade (1941)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1299    'Til There Was You (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1300    Stripes (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8
1301    Late Bloomers (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
1302    Getaway, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1303    New York Cop (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1304    National Lampoon's Senior Trip (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1305    Delta of Venus (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1306    Carmen Miranda: Bananas Is My Business (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1307    Babyfever (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1308    Very Natural Thing, A (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1309    Walk in the Sun, A (1945)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1310    Waiting to Exhale (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1311    Pompatus of Love, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1312    Palmetto (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.142857142857143
1313    Surviving the Game (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4545454545454546
1314    Inventing the Abbotts (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.130434782608696
1315    Horse Whisperer, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7142857142857144
1316    Journey of August King, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1317    Catwalk (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.3333333333333333
1318    Neon Bible, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.75
1319    Homage (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1320    Open Season (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1321    Metisse (Café au Lait) (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1322    Wooden Man's Bride, The (Wu Kui) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1323    Loaded (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
1324    August (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1325    Boys (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1326    Captives (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1327    Of Love and Shadows (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
1328    Low Life, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1329    An Unforgettable Summer (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1330    Last Klezmer: Leopold Kozlowski, His Life and ...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1331    My Life and Times With Antonin Artaud (En comp...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1332    Midnight Dancers (Sibak) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1333    Somebody to Love (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1334    American Buffalo (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6363636363636362
1335    Kazaam (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.8
1336    Larger Than Life (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1337    Two Deaths (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1338    Stefano Quantestorie (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1339    Crude Oasis, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1340    Hedd Wyn (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1341    Convent, The (Convento, O) (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1342    Lotto Land (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1343    Story of Xinghua, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
1344    Day the Sun Turned Cold, The (Tianguo niezi) (...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1345    Dingo (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
1346    Ballad of Narayama, The (Narayama Bushiko) (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1347    Every Other Weekend (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1348    Mille bolle blu (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1349    Crows and Sparrows (1949)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1350    Lover's Knot (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1351    Shadow of Angels (Schatten der Engel) (1976)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1352    1-900 (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
1353    Venice/Venice (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1354    Infinity (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1355    Ed's Next Move (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1356    For the Moment (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1357    The Deadly Cure (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1358    Boys in Venice (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1359    Sexual Life of the Belgians, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1360    Search for One-eye Jimmy, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1361    American Strays (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1362    Leopard Son, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1363    Bird of Prey (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1364    Johnny 100 Pesos (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1365    JLG/JLG - autoportrait de décembre (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1366    Faust (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.2
1367    Mina Tannenbaum (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1368    Forbidden Christ, The (Cristo proibito, Il) (1...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1369    I Can't Sleep (J'ai pas sommeil) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1370    Machine, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1371    Stranger, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1372    Good Morning (1971)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1373    Falling in Love Again (1980)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1374    Cement Garden, The (1993)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6
1375    Meet Wally Sparks (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.142857142857143
1376    Hotel de Love (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1377    Rhyme & Reason (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2
1378    Love and Other Catastrophes (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.857142857142857
1379    Hollow Reed (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1380    Losing Chase (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1381    Bonheur, Le (1965)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1382    Second Jungle Book: Mowgli & Baloo, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1383    Squeeze (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6666666666666667
1384    Roseanna's Grave (For Roseanna) (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1385    Tetsuo II: Body Hammer (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1386    Fall (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1387    Gabbeh (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1388    Mondo (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1389    Innocent Sleep, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1390    For Ever Mozart (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1391    Locusts, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1392    Stag (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.111111111111111
1393    Swept from the Sea (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1394    Hurricane Streets (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1395    Stonewall (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.2
1396    Of Human Bondage (1934)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
1397    Anna (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.5
1398    Stranger in the House (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1399    Picture Bride (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1
1400    M. Butterfly (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2222222222222223
1401    Ciao, Professore! (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1402    Caro Diario (Dear Diary) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1403    Withnail and I (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.230769230769231
1404    Boy's Life 2 (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1405    When Night Is Falling (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
1406    Specialist, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1407    Gordy (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1408    Swan Princess, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.857142857142857
1409    Harlem (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1410    Barbarella (1968)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5714285714285716
1411    Land Before Time III: The Time of the Great Gi...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6666666666666667
1412    Street Fighter (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1413    Coldblooded (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1414    Next Karate Kid, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4444444444444446
1415    No Escape (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
1416    Turning, The (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1417    Joy Luck Club, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1418    Highlander III: The Sorcerer (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.125
1419    Gilligan's Island: The Movie (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.3333333333333333
1420    My Crazy Life (Mi vida loca) (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1818181818181817
1421    Suture (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1422    Walking Dead, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1423    I Like It Like That (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1424    I'll Do Anything (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
1425    Grace of My Heart (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1426    Drunks (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1427    SubUrbia (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1428    Sliding Doors (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1429    Ill Gotten Gains (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1430    Legal Deceit (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4
1431    Mighty, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1432    Men of Means (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1433    Shooting Fish (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1434    Steal Big, Steal Little (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5714285714285716
1435    Mr. Jones (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1436    House Party 3 (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1437    Panther (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
1438    Jason's Lyric (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1439    Above the Rim (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1440    Moonlight and Valentino (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5714285714285716
1441    Scarlet Letter, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4
1442    8 Seconds (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
1443    That Darn Cat! (1965)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.473684210526316
1444    Ladybird Ladybird (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1445    Bye Bye, Love (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1333333333333333
1446    Century (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1447    My Favorite Season (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1448    Pather Panchali (1955)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.625
1449    Golden Earrings (1947)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1450    Foreign Correspondent (1940)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.8666666666666667
1451    Lady of Burlesque (1943)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1452    Angel on My Shoulder (1946)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1453    Angel and the Badman (1947)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1454    Outlaw, The (1943)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1455    Beat the Devil (1954)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7142857142857144
1456    Love Is All There Is (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1457    Damsel in Distress, A (1937)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1458    Madame Butterfly (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5714285714285716
1459    Sleepover (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1460    Here Comes Cookie (1935)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1461    Thieves (Voleurs, Les) (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.7142857142857144
1462    Boys, Les (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1463    Stars Fell on Henrietta, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1464    Last Summer in the Hamptons (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1465    Margaret's Museum (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1466    Saint of Fort Washington, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1467    Cure, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1468    Tom and Huck (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
1469    Gumby: The Movie (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
1470    Hideaway (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4444444444444446
1471    Visitors, The (Visiteurs, Les) (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1472    Little Princess, The (1939)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5555555555555554
1473    Nina Takes a Lover (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8333333333333335
1474    Bhaji on the Beach (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.875
1475    Raw Deal (1948)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1476    Nightwatch (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1477    Dead Presidents (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.7222222222222223
1478    Reckless (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1479    Herbie Rides Again (1974)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.272727272727273
1480    S.F.W. (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1481    Gate of Heavenly Peace, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1482    Man in the Iron Mask, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.4166666666666665
1483    Jerky Boys, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1484    Colonel Chabert, Le (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1485    Girl in the Cadillac (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1486    Even Cowgirls Get the Blues (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1487    Germinal (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1488    Chasers (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.2
1489    Fausto (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1490    Tough and Deadly (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1491    Window to Paris (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1492    Modern Affair, A (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1493    Mostro, Il (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1494    Flirt (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6
1495    Carpool (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1496    Line King: Al Hirschfeld, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1497    Farmer & Chase (1995)

Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1498    Grosse Fatigue (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1499    Santa with Muscles (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1500    Prisoner of the Mountains (Kavkazsky Plennik) ...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1501    Naked in New York (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1502    Gold Diggers: The Secret of Bear Mountain (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1
1503    Bewegte Mann, Der (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1504    Killer: A Journal of Murder (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1505    Nelly & Monsieur Arnaud (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6666666666666665
1506    Three Lives and Only One Death (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1507    Babysitter, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1508    Getting Even with Dad (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6
1509    Mad Dog Time (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1510    Children of the Revolution (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2
1511    World of Apu, The (Apur Sansar) (1959)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1512    Sprung (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1513    Dream With the Fishes (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.142857142857143
1514    Wings of Courage (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1515    Wedding Gift, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1516    Race the Sun (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1517    Losing Isaiah (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1518    New Jersey Drive (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1519    Fear, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1520    Mr. Wonderful (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1521    Trial by Jury (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1522    Good Man in Africa, A (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1523    Kaspar Hauser (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.25
1524    Object of My Affection, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1525    Witness (1985)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1526    Senseless (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.4285714285714284
1527    Nowhere (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1528    Underground (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1529    Jefferson in Paris (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1530    Far From Home: The Adventures of Yellow Dog (1...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2857142857142856
1531    Foreign Student (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1532    I Don't Want to Talk About It (De eso no se ha...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1533    Twin Town (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.1666666666666665
1534    Enfer, L' (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1535    Aiqing wansui (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1536    Cosi (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1537    All Over Me (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1538    Being Human (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.75
1539    Amazing Panda Adventure, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.8
1540    Beans of Egypt, Maine, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1541    Scarlet Letter, The (1926)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1542    Johns (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1543    It Takes Two (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6666666666666665
1544    Frankie Starlight (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1545    Shadows (Cienie) (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1546    Show, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1547    The Courtyard (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1548    Dream Man (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1549    Destiny Turns on the Radio (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1550    Glass Shield, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1551    Hunted, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1552    Underneath, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1553    Safe Passage (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1554    Secret Adventures of Tom Thumb, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.6
1555    Condition Red (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1556    Yankee Zulu (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1557    Aparajito (1956)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5714285714285716
1558    Hostile Intentions (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1559    Clean Slate (Coup de Torchon) (1981)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.75
1560    Tigrero: A Film That Was Never Made (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1561    Eye of Vichy, The (Oeil de Vichy, L') (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1562    Promise, The (Versprechen, Das) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1563    To Cross the Rubicon (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1564    Daens (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1565    Man from Down Under, The (1943)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1566    Careful (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1567    Vermont Is For Lovers (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1568    Vie est belle, La (Life is Rosey) (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1569    Quartier Mozart (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1570    Touki Bouki (Journey of the Hyena) (1973)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1571    Wend Kuuni (God's Gift) (1982)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1572    Spirits of the Dead (Tre passi nel delirio) (1...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1573    Pharaoh's Army (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1574    I, Worst of All (Yo, la peor de todas) (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1575    Hungarian Fairy Tale, A (1987)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1576    Death in the Garden (Mort en ce jardin, La) (1...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1577    Collectionneuse, La (1967)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1578    Baton Rouge (1988)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1579    Liebelei (1933)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1580    Woman in Question, The (1950)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1581    T-Men (1947)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1582    Invitation, The (Zaproszenie) (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1583    Symphonie pastorale, La (1946)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1584    American Dream (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1585    Lashou shentan (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1586    Terror in a Texas Town (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1587    Salut cousin! (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1588    Schizopolis (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1589    To Have, or Not (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1590    Duoluo tianshi (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.1666666666666665
1591    Magic Hour, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.6
1592    Death in Brunswick (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1593    Everest (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.5
1594    Shopping (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1595    Nemesis 2: Nebula (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1596    Romper Stomper (1992)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1597    City of Industry (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1598    Someone Else's America (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1599    Guantanamera (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
1600    Office Killer (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1601    Price Above Rubies, A (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1602    Angela (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1603    He Walked by Night (1948)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1604    Love Serenade (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1605    Deceiver (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1606    Hurricane Streets (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.3333333333333335
1607    Buddy (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.25
1608    B*A*P*S (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6666666666666667
1609    Truth or Consequences, N.M. (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1610    Intimate Relations (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1611    Leading Man, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
1612    Tokyo Fist (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1613    Reluctant Debutante, The (1958)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1614    Warriors of Virtue (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1615    Desert Winds (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1616    Hugo Pool (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1617    King of New York (1990)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1618    All Things Fair (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1619    Sixth Man, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.2222222222222223
1620    Butterfly Kiss (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0

1621    Paris, France (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.3333333333333335
1622    Cérémonie, La (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1623    Hush (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1624    Nightwatch (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1625    Nobody Loves Me (Keiner liebt mich) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1626    Wife, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1627    Lamerica (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
1628    Nico Icon (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1629    Silence of the Palace, The (Saimt el Qusur) (1...
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1630    Slingshot, The (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1631    Land and Freedom (Tierra y libertad) (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1632    Á köldum klaka (Cold Fever) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1633    Etz Hadomim Tafus (Under the Domin Tree) (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1634    Two Friends (1986)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1635    Brothers in Trouble (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1636    Girls Town (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1637    Normal Life (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1638    Bitter Sugar (Azucar Amargo) (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.333333333333333
1639    Eighth Day, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1640    Dadetown (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1641    Some Mother's Son (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.5
1642    Angel Baby (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.75
1643    Sudden Manhattan (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.5
1644    Butcher Boy, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1645    Men With Guns (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1646    Hana-bi (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1647    Niagara, Niagara (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1648    Big One, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1649    Butcher Boy, The (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1650    Spanish Prisoner, The (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1651    Temptress Moon (Feng Yue) (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.6666666666666667
1652    Entertaining Angels: The Dorothy Day Story (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  5.0
1653    Chairman of the Board (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1654    Favor, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1655    Little City (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.5
1656    Target (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1657    Substance of Fire, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1658    Getting Away With Murder (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1659    Small Faces (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1660    New Age, The (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1661    Rough Magic (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.5
1662    Nothing Personal (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1663    8 Heads in a Duffel Bag (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.25
1664    Brother's Kiss, A (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1665    Ripe (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1666    Next Step, The (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1667    Wedding Bell Blues (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1668    MURDER and murder (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1669    Tainted (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1670    Further Gesture, A (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1671    Kika (1993)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1672    Mirage (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1673    Mamma Roma (1962)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  4.0
1674    Sunchaser, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1675    War at Home, The (1996)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1676    Sweet Nothing (1995)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1677    Mat' i syn (1997)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  1.0
1678    B. Monkey (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1679    Sliding Doors (1998)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  2.0
1680    You So Crazy (1994)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
1681    Scream of Stone (Schrei aus Stein) (1991)
Name: title, dtype: object -- AVERAGE RATING OF MOVIE =  3.0
MAXIMUM RATING IS  5.0


812    Celluloid Closet, The (1995)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1120    Umbrellas of Cherbourg, The (Parapluies de Che...
Name: title, dtype: object ****** HAS A HIGH RATING *******
1187    Young Guns II (1990)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1199    Kim (1950)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1291    Simple Wish, A (1997)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1465    Margaret's Museum (1995)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1498    Grosse Fatigue (1994)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1534    Enfer, L' (1994)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1597    City of Industry (1997)
Name: title, dtype: object ****** HAS A HIGH RATING *******
1651    Temptress Moon (Feng Yue) (1996)
Name: title, dtype: object ****** HAS A HIGH RATING *******


Good movie ids:
813 ****** GOOD MOVIE IDS *******
1121 ****** GOOD MOVIE IDS *******
1188 ****** GOOD MOVIE IDS *******
1200 ****** GOOD MOVIE IDS *******
1292 ****** GOOD MOVIE IDS *******
1466 ****** GOOD MOVIE IDS *******
1499 ****** GOOD MOVIE IDS *******
1535 ****** GOOD MOVIE IDS *******
1598 ****** GOOD MOVIE IDS *******
1652 ****** GOOD MOVIE IDS *******


Best movie titles
812    Celluloid Closet, The (1995)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1120    Umbrellas of Cherbourg, The (Parapluies de Che...
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1187    Young Guns II (1990)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1199    Kim (1950)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1291    Simple Wish, A (1997)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1465    Margaret's Museum (1995)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1498    Grosse Fatigue (1994)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1534    Enfer, L' (1994)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1597    City of Industry (1997)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
1651    Temptress Moon (Feng Yue) (1996)
Name: title, dtype: object ****** BEST MOVIE TITLES *******
Number of ratings per movie
movie_id 1 number of ratings 1753
movie_id 2 number of ratings 420
movie_id 3 number of ratings 273
movie_id 4 number of ratings 742
movie_id 5 number of ratings 284
movie_id 6 number of ratings 93
movie_id 7 number of ratings 1489
movie_id 8 number of ratings 875
movie_id 9 number of ratings 1165
movie_id 10 number of ratings 341
movie_id 11 number of ratings 908
movie_id 12 number of ratings 1171
movie_id 13 number of ratings 629
movie_id 14 number of ratings 726
movie_id 15 number of ratings 1107
movie_id 16 number of ratings 125
movie_id 17 number of ratings 287
movie_id 18 number of ratings 28
movie_id 19 number of ratings 273
movie_id 20 number of ratings 246
movie_id 21 number of ratings 232
movie_id 22 number of ratings 1233
movie_id 23 number of ratings 750
movie_id 24 number of ratings 600
movie_id 25 number of ratings 1009
movie_id 26 number of ratings 252
movie_id 27 number of ratings 177
movie_id 28 number of ratings 1085
movie_id 29 number of ratings 304
movie_id 30 number of ratings 146
movie_id 31 number of ratings 559
movie_id 32 number of ratings 307
movie_id 33 number of ratings 335
movie_id 34 number of ratings 19
movie_id 35 number of ratings 24
movie_id 36 number of ratings 28
movie_id 37 number of ratings 18
movie_id 38 number of ratings 361
movie_id 39 number of ratings 284
movie_id 40 number of ratings 165
movie_id 41 number of ratings 114
movie_id 42 number of ratings 563
movie_id 43 number of ratings 120
movie_id 44 number of ratings 264
movie_id 45 number of ratings 324
movie_id 46 number of ratings 96
movie_id 47 number of ratings 479
movie_id 48 number of ratings 479
movie_id 49 number of ratings 269
movie_id 50 number of ratings 2541
movie_id 51 number of ratings 280
movie_id 52 number of ratings 343
movie_id 53 number of ratings 378
movie_id 54 number of ratings 337
movie_id 55 number of ratings 552
movie_id 56 number of ratings 1600
movie_id 57 number of ratings 160
movie_id 58 number of ratings 638
movie_id 59 number of ratings 337
movie_id 60 number of ratings 257
movie_id 61 number of ratings 228
movie_id 62 number of ratings 399
movie_id 63 number of ratings 254
movie_id 64 number of ratings 1258
movie_id 65 number of ratings 407
movie_id 66 number of ratings 575
movie_id 67 number of ratings 314
movie_id 68 number of ratings 458
movie_id 69 number of ratings 1237
movie_id 70 number of ratings 919
movie_id 71 number of ratings 832
movie_id 72 number of ratings 412
movie_id 73 number of ratings 444
movie_id 74 number of ratings 21
movie_id 75 number of ratings 15
movie_id 76 number of ratings 184
movie_id 77 number of ratings 495
movie_id 78 number of ratings 81
movie_id 79 number of ratings 1359
movie_id 80 number of ratings 188
movie_id 81 number of ratings 391
movie_id 82 number of ratings 971
movie_id 83 number of ratings 715
movie_id 84 number of ratings 54
movie_id 85 number of ratings 176
movie_id 86 number of ratings 591
movie_id 87 number of ratings 539
movie_id 88 number of ratings 754
movie_id 89 number of ratings 1138
movie_id 90 number of ratings 290
movie_id 91 number of ratings 513
movie_id 92 number of ratings 376
movie_id 93 number of ratings 417
movie_id 94 number of ratings 423
movie_id 95 number of ratings 835
movie_id 96 number of ratings 1182
movie_id 97 number of ratings 971
movie_id 98 number of ratings 1673
movie_id 99 number of ratings 638
movie_id 100 number of ratings 2111
movie_id 101 number of ratings 238
movie_id 102 number of ratings 169
movie_id 103 number of ratings 28
movie_id 104 number of ratings 7
movie_id 105 number of ratings 190
movie_id 106 number of ratings 205
movie_id 107 number of ratings 147
movie_id 108 number of ratings 200
movie_id 109 number of ratings 446
movie_id 110 number of ratings 78
movie_id 111 number of ratings 948
movie_id 112 number of ratings 49
movie_id 113 number of ratings 37
movie_id 114 number of ratings 298
movie_id 115 number of ratings 56
movie_id 116 number of ratings 478
movie_id 117 number of ratings 1396
movie_id 118 number of ratings 942
movie_id 119 number of ratings 18
movie_id 120 number of ratings 150
movie_id 121 number of ratings 1475
movie_id 122 number of ratings 248
movie_id 123 number of ratings 372
movie_id 124 number of ratings 758
movie_id 125 number of ratings 868
movie_id 126 number of ratings 369
movie_id 127 number of ratings 1769
movie_id 128 number of ratings 230
movie_id 129 number of ratings 493
movie_id 130 number of ratings 52
movie_id 131 number of ratings 354
movie_id 132 number of ratings 1003
movie_id 133 number of ratings 662
movie_id 134 number of ratings 850
movie_id 135 number of ratings 1028
movie_id 136 number of ratings 433
movie_id 137 number of ratings 667
movie_id 138 number of ratings 49
movie_id 139 number of ratings 139
movie_id 140 number of ratings 196
movie_id 141 number of ratings 252
movie_id 142 number of ratings 175
movie_id 143 number of ratings 836
movie_id 144 number of ratings 941
movie_id 145 number of ratings 159
movie_id 146 number of ratings 25
movie_id 147 number of ratings 642
movie_id 148 number of ratings 410
movie_id 149 number of ratings 69
movie_id 150 number of ratings 601
movie_id 151 number of ratings 1184
movie_id 152 number of ratings 298
movie_id 153 number of ratings 935
movie_id 154 number of ratings 652
movie_id 155 number of ratings 304
movie_id 156 number of ratings 590
movie_id 157 number of ratings 469
movie_id 158 number of ratings 157
movie_id 159 number of ratings 326
movie_id 160 number of ratings 239
movie_id 161 number of ratings 766
movie_id 162 number of ratings 377
movie_id 163 number of ratings 327
movie_id 164 number of ratings 542
movie_id 165 number of ratings 263
movie_id 166 number of ratings 239
movie_id 167 number of ratings 198
movie_id 168 number of ratings 1285
movie_id 169 number of ratings 527
movie_id 170 number of ratings 505
movie_id 171 number of ratings 252
movie_id 172 number of ratings 1543
movie_id 173 number of ratings 1352
movie_id 174 number of ratings 1786
movie_id 175 number of ratings 794
movie_id 176 number of ratings 1121
movie_id 177 number of ratings 529
movie_id 178 number of ratings 543
movie_id 179 number of ratings 864
movie_id 180 number of ratings 894
movie_id 181 number of ratings 2032
movie_id 182 number of ratings 893
movie_id 183 number of ratings 1174
movie_id 184 number of ratings 398
movie_id 185 number of ratings 980
movie_id 186 number of ratings 963
movie_id 187 number of ratings 875
movie_id 188 number of ratings 626
movie_id 189 number of ratings 271
movie_id 190 number of ratings 513
movie_id 191 number of ratings 1149
movie_id 192 number of ratings 478
movie_id 193 number of ratings 615
movie_id 194 number of ratings 978
movie_id 195 number of ratings 1184
movie_id 196 number of ratings 983
movie_id 197 number of ratings 981
movie_id 198 number of ratings 509
movie_id 199 number of ratings 689
movie_id 200 number of ratings 788
movie_id 201 number of ratings 313
movie_id 202 number of ratings 1054
movie_id 203 number of ratings 704
movie_id 204 number of ratings 1342
movie_id 205 number of ratings 543
movie_id 206 number of ratings 169
movie_id 207 number of ratings 252
movie_id 208 number of ratings 789
movie_id 209 number of ratings 746
movie_id 210 number of ratings 1301
movie_id 211 number of ratings 806
movie_id 212 number of ratings 318
movie_id 213 number of ratings 534
movie_id 214 number of ratings 382
movie_id 215 number of ratings 784
movie_id 216 number of ratings 1134
movie_id 217 number of ratings 379
movie_id 218 number of ratings 591
movie_id 219 number of ratings 352
movie_id 220 number of ratings 222
movie_id 221 number of ratings 276
movie_id 222 number of ratings 1336
movie_id 223 number of ratings 571
movie_id 224 number of ratings 163
movie_id 225 number of ratings 317
movie_id 226 number of ratings 557
movie_id 227 number of ratings 528
movie_id 228 number of ratings 931
movie_id 229 number of ratings 532
movie_id 230 number of ratings 686
movie_id 231 number of ratings 381
movie_id 232 number of ratings 324
movie_id 233 number of ratings 408
movie_id 234 number of ratings 1057
movie_id 235 number of ratings 618
movie_id 236 number of ratings 163
movie_id 237 number of ratings 1425
movie_id 238 number of ratings 992
movie_id 239 number of ratings 527
movie_id 240 number of ratings 435
movie_id 241 number of ratings 454
movie_id 242 number of ratings 467
movie_id 243 number of ratings 322
movie_id 244 number of ratings 152
movie_id 245 number of ratings 746
movie_id 246 number of ratings 488
movie_id 247 number of ratings 9
movie_id 248 number of ratings 588
movie_id 249 number of ratings 422
movie_id 250 number of ratings 685
movie_id 251 number of ratings 196
movie_id 252 number of ratings 465
movie_id 253 number of ratings 96
movie_id 254 number of ratings 152
movie_id 255 number of ratings 578
movie_id 256 number of ratings 57
movie_id 257 number of ratings 1135
movie_id 258 number of ratings 1936
movie_id 259 number of ratings 435
movie_id 260 number of ratings 327
movie_id 261 number of ratings 110
movie_id 262 number of ratings 245
movie_id 263 number of ratings 41
movie_id 264 number of ratings 277
movie_id 265 number of ratings 877
movie_id 266 number of ratings 95
movie_id 267 number of ratings 31
movie_id 268 number of ratings 967
movie_id 269 number of ratings 1237
movie_id 270 number of ratings 489
movie_id 271 number of ratings 682
movie_id 272 number of ratings 844
movie_id 273 number of ratings 796
movie_id 274 number of ratings 665
movie_id 275 number of ratings 1075
movie_id 276 number of ratings 1102
movie_id 277 number of ratings 246
movie_id 278 number of ratings 194
movie_id 279 number of ratings 92
movie_id 280 number of ratings 271
movie_id 281 number of ratings 459
movie_id 282 number of ratings 855
movie_id 283 number of ratings 658
movie_id 284 number of ratings 610
movie_id 285 number of ratings 691
movie_id 286 number of ratings 1759
movie_id 287 number of ratings 280
movie_id 288 number of ratings 1645
movie_id 289 number of ratings 772
movie_id 290 number of ratings 299
movie_id 291 number of ratings 428
movie_id 292 number of ratings 418
movie_id 293 number of ratings 559
movie_id 294 number of ratings 1531
movie_id 295 number of ratings 262
movie_id 296 number of ratings 20
movie_id 297 number of ratings 198
movie_id 298 number of ratings 731
movie_id 299 number of ratings 214
movie_id 300 number of ratings 1565
movie_id 301 number of ratings 760
movie_id 302 number of ratings 1236
movie_id 303 number of ratings 494
movie_id 304 number of ratings 527
movie_id 305 number of ratings 317
movie_id 306 number of ratings 379
movie_id 307 number of ratings 661
movie_id 308 number of ratings 89
movie_id 309 number of ratings 80
movie_id 310 number of ratings 522
movie_id 311 number of ratings 276
movie_id 312 number of ratings 253
movie_id 313 number of ratings 1486
movie_id 314 number of ratings 5
movie_id 315 number of ratings 656
movie_id 316 number of ratings 470
movie_id 317 number of ratings 399
movie_id 318 number of ratings 1331
movie_id 319 number of ratings 550
movie_id 320 number of ratings 81
movie_id 321 number of ratings 529
movie_id 322 number of ratings 673
movie_id 323 number of ratings 704
movie_id 324 number of ratings 392
movie_id 325 number of ratings 326
movie_id 326 number of ratings 588
movie_id 327 number of ratings 591

movie_id 328 number of ratings 1010
movie_id 329 number of ratings 150
movie_id 330 number of ratings 124
movie_id 331 number of ratings 400
movie_id 332 number of ratings 495
movie_id 333 number of ratings 902
movie_id 334 number of ratings 215
movie_id 335 number of ratings 58
movie_id 336 number of ratings 113
movie_id 337 number of ratings 54
movie_id 338 number of ratings 242
movie_id 339 number of ratings 153
movie_id 340 number of ratings 678
movie_id 341 number of ratings 34
movie_id 342 number of ratings 152
movie_id 343 number of ratings 384
movie_id 344 number of ratings 201
movie_id 345 number of ratings 221
movie_id 346 number of ratings 459
movie_id 347 number of ratings 481
movie_id 348 number of ratings 89
movie_id 349 number of ratings 90
movie_id 350 number of ratings 129
movie_id 351 number of ratings 54
movie_id 352 number of ratings 55
movie_id 353 number of ratings 34
movie_id 354 number of ratings 251
movie_id 355 number of ratings 120
movie_id 356 number of ratings 328
movie_id 357 number of ratings 1133
movie_id 358 number of ratings 374
movie_id 359 number of ratings 63
movie_id 360 number of ratings 32
movie_id 361 number of ratings 35
movie_id 362 number of ratings 79
movie_id 363 number of ratings 128
movie_id 364 number of ratings 99
movie_id 365 number of ratings 154
movie_id 366 number of ratings 157
movie_id 367 number of ratings 588
movie_id 368 number of ratings 59
movie_id 369 number of ratings 145
movie_id 370 number of ratings 110
movie_id 371 number of ratings 212
movie_id 372 number of ratings 120
movie_id 373 number of ratings 113
movie_id 374 number of ratings 25
movie_id 375 number of ratings 45
movie_id 376 number of ratings 68
movie_id 377 number of ratings 28
movie_id 378 number of ratings 376
movie_id 379 number of ratings 128
movie_id 380 number of ratings 387
movie_id 381 number of ratings 355
movie_id 382 number of ratings 399
movie_id 383 number of ratings 64
movie_id 384 number of ratings 192
movie_id 385 number of ratings 741
movie_id 386 number of ratings 245
movie_id 387 number of ratings 220
movie_id 388 number of ratings 67
movie_id 389 number of ratings 93
movie_id 390 number of ratings 32
movie_id 391 number of ratings 162
movie_id 392 number of ratings 241
movie_id 393 number of ratings 655
movie_id 394 number of ratings 40
movie_id 395 number of ratings 145
movie_id 396 number of ratings 152
movie_id 397 number of ratings 31
movie_id 398 number of ratings 54
movie_id 399 number of ratings 294
movie_id 400 number of ratings 49
movie_id 401 number of ratings 213
movie_id 402 number of ratings 589
movie_id 403 number of ratings 689
movie_id 404 number of ratings 371
movie_id 405 number of ratings 1140
movie_id 406 number of ratings 120
movie_id 407 number of ratings 108
movie_id 408 number of ratings 503
movie_id 409 number of ratings 220
movie_id 410 number of ratings 507
movie_id 411 number of ratings 475
movie_id 412 number of ratings 223
movie_id 413 number of ratings 145
movie_id 414 number of ratings 219
movie_id 415 number of ratings 71
movie_id 416 number of ratings 223
movie_id 417 number of ratings 226
movie_id 418 number of ratings 462
movie_id 419 number of ratings 663
movie_id 420 number of ratings 297
movie_id 421 number of ratings 381
movie_id 422 number of ratings 74
movie_id 423 number of ratings 1150
movie_id 424 number of ratings 25
movie_id 425 number of ratings 318
movie_id 426 number of ratings 91
movie_id 427 number of ratings 940
movie_id 428 number of ratings 462
movie_id 429 number of ratings 382
movie_id 430 number of ratings 372
movie_id 431 number of ratings 541
movie_id 432 number of ratings 656
movie_id 433 number of ratings 631
movie_id 434 number of ratings 257
movie_id 435 number of ratings 853
movie_id 436 number of ratings 350
movie_id 437 number of ratings 5
movie_id 438 number of ratings 7
movie_id 439 number of ratings 5
movie_id 440 number of ratings 23
movie_id 441 number of ratings 136
movie_id 442 number of ratings 5
movie_id 443 number of ratings 617
movie_id 444 number of ratings 125
movie_id 445 number of ratings 77
movie_id 446 number of ratings 22
movie_id 447 number of ratings 424
movie_id 448 number of ratings 288
movie_id 449 number of ratings 355
movie_id 450 number of ratings 151
movie_id 451 number of ratings 569
movie_id 452 number of ratings 176
movie_id 453 number of ratings 31
movie_id 454 number of ratings 46
movie_id 455 number of ratings 472
movie_id 456 number of ratings 111
movie_id 457 number of ratings 47
movie_id 458 number of ratings 281
movie_id 459 number of ratings 90
movie_id 460 number of ratings 84
movie_id 461 number of ratings 268
movie_id 462 number of ratings 563
movie_id 463 number of ratings 274
movie_id 464 number of ratings 97
movie_id 465 number of ratings 303
movie_id 466 number of ratings 187
movie_id 467 number of ratings 182
movie_id 468 number of ratings 212
movie_id 469 number of ratings 253
movie_id 470 number of ratings 396
movie_id 471 number of ratings 798
movie_id 472 number of ratings 487
movie_id 473 number of ratings 394
movie_id 474 number of ratings 825
movie_id 475 number of ratings 971
movie_id 476 number of ratings 483
movie_id 477 number of ratings 305
movie_id 478 number of ratings 428
movie_id 479 number of ratings 761
movie_id 480 number of ratings 767
movie_id 481 number of ratings 248
movie_id 482 number of ratings 510
movie_id 483 number of ratings 1083
movie_id 484 number of ratings 581
movie_id 485 number of ratings 477
movie_id 486 number of ratings 243
movie_id 487 number of ratings 279
movie_id 488 number of ratings 273
movie_id 489 number of ratings 214
movie_id 490 number of ratings 201
movie_id 491 number of ratings 254
movie_id 492 number of ratings 228
movie_id 493 number of ratings 249
movie_id 494 number of ratings 224
movie_id 495 number of ratings 216
movie_id 496 number of ratings 952
movie_id 497 number of ratings 261
movie_id 498 number of ratings 636
movie_id 499 number of ratings 245
movie_id 500 number of ratings 121
movie_id 501 number of ratings 430
movie_id 502 number of ratings 211
movie_id 503 number of ratings 142
movie_id 504 number of ratings 466
movie_id 505 number of ratings 272
movie_id 506 number of ratings 347
movie_id 507 number of ratings 374
movie_id 508 number of ratings 773
movie_id 509 number of ratings 466
movie_id 510 number of ratings 477
movie_id 511 number of ratings 732
movie_id 512 number of ratings 228
movie_id 513 number of ratings 312
movie_id 514 number of ratings 704
movie_id 515 number of ratings 845
movie_id 516 number of ratings 250
movie_id 517 number of ratings 343
movie_id 518 number of ratings 325
movie_id 519 number of ratings 328
movie_id 520 number of ratings 509
movie_id 521 number of ratings 460
movie_id 522 number of ratings 132
movie_id 523 number of ratings 655
movie_id 524 number of ratings 185
movie_id 525 number of ratings 294
movie_id 526 number of ratings 475
movie_id 527 number of ratings 784
movie_id 528 number of ratings 500
movie_id 529 number of ratings 370
movie_id 530 number of ratings 322
movie_id 531 number of ratings 506
movie_id 532 number of ratings 73
movie_id 533 number of ratings 55
movie_id 534 number of ratings 43
movie_id 535 number of ratings 171
movie_id 536 number of ratings 33
movie_id 537 number of ratings 109
movie_id 538 number of ratings 226
movie_id 539 number of ratings 109
movie_id 540 number of ratings 108
movie_id 541 number of ratings 141
movie_id 542 number of ratings 129
movie_id 543 number of ratings 76
movie_id 544 number of ratings 224
movie_id 545 number of ratings 22
movie_id 546 number of ratings 770
movie_id 547 number of ratings 137
movie_id 548 number of ratings 26
movie_id 549 number of ratings 328
movie_id 550 number of ratings 496
movie_id 551 number of ratings 58
movie_id 552 number of ratings 129
movie_id 553 number of ratings 207
movie_id 554 number of ratings 286
movie_id 555 number of ratings 20
movie_id 556 number of ratings 30
movie_id 557 number of ratings 53
movie_id 558 number of ratings 257
movie_id 559 number of ratings 436
movie_id 560 number of ratings 60
movie_id 561 number of ratings 181
movie_id 562 number of ratings 154
movie_id 563 number of ratings 70
movie_id 564 number of ratings 55
movie_id 565 number of ratings 59
movie_id 566 number of ratings 639
movie_id 567 number of ratings 98
movie_id 568 number of ratings 839
movie_id 569 number of ratings 181
movie_id 570 number of ratings 155
movie_id 571 number of ratings 70
movie_id 572 number of ratings 80
movie_id 573 number of ratings 97
movie_id 574 number of ratings 33
movie_id 575 number of ratings 112
movie_id 576 number of ratings 281
movie_id 577 number of ratings 91
movie_id 578 number of ratings 290
movie_id 579 number of ratings 50
movie_id 580 number of ratings 108
movie_id 581 number of ratings 190
movie_id 582 number of ratings 605
movie_id 583 number of ratings 111
movie_id 584 number of ratings 280
movie_id 585 number of ratings 97
movie_id 586 number of ratings 91
movie_id 587 number of ratings 50
movie_id 588 number of ratings 766
movie_id 589 number of ratings 173
movie_id 590 number of ratings 36
movie_id 591 number of ratings 641
movie_id 592 number of ratings 30
movie_id 593 number of ratings 38
movie_id 594 number of ratings 12
movie_id 595 number of ratings 198
movie_id 596 number of ratings 429
movie_id 597 number of ratings 649
movie_id 598 number of ratings 9
movie_id 599 number of ratings 1
movie_id 600 number of ratings 6
movie_id 601 number of ratings 80
movie_id 602 number of ratings 185
movie_id 603 number of ratings 917
movie_id 604 number of ratings 325
movie_id 605 number of ratings 104
movie_id 606 number of ratings 267
movie_id 607 number of ratings 262
movie_id 608 number of ratings 118
movie_id 609 number of ratings 215
movie_id 610 number of ratings 150
movie_id 611 number of ratings 164
movie_id 612 number of ratings 134
movie_id 613 number of ratings 109
movie_id 614 number of ratings 191
movie_id 615 number of ratings 239
movie_id 616 number of ratings 219
movie_id 617 number of ratings 68
movie_id 618 number of ratings 65
movie_id 619 number of ratings 203
movie_id 620 number of ratings 133
movie_id 621 number of ratings 32
movie_id 622 number of ratings 131
movie_id 623 number of ratings 114
movie_id 624 number of ratings 72
movie_id 625 number of ratings 273
movie_id 626 number of ratings 13
movie_id 627 number of ratings 242
movie_id 628 number of ratings 594
movie_id 629 number of ratings 257
movie_id 630 number of ratings 102
movie_id 631 number of ratings 431
movie_id 632 number of ratings 226
movie_id 633 number of ratings 280
movie_id 634 number of ratings 90
movie_id 635 number of ratings 63
movie_id 636 number of ratings 295
movie_id 637 number of ratings 115
movie_id 638 number of ratings 166
movie_id 639 number of ratings 148
movie_id 640 number of ratings 248
movie_id 641 number of ratings 139
movie_id 642 number of ratings 310
movie_id 643 number of ratings 12
movie_id 644 number of ratings 132
movie_id 645 number of ratings 103
movie_id 646 number of ratings 147
movie_id 647 number of ratings 287
movie_id 648 number of ratings 270
movie_id 649 number of ratings 170
movie_id 650 number of ratings 255
movie_id 651 number of ratings 697
movie_id 652 number of ratings 350
movie_id 653 number of ratings 133
movie_id 654 number of ratings 608
movie_id 655 number of ratings 881
movie_id 656 number of ratings 176
movie_id 657 number of ratings 558
movie_id 658 number of ratings 270
movie_id 659 number of ratings 469
movie_id 660 number of ratings 576
movie_id 661 number of ratings 361
movie_id 662 number of ratings 281
movie_id 663 number of ratings 453
movie_id 664 number of ratings 163
movie_id 665 number of ratings 283
movie_id 666 number of ratings 12
movie_id 667 number of ratings 26
movie_id 668 number of ratings 13
movie_id 669 number of ratings 21
movie_id 670 number of ratings 108
movie_id 671 number of ratings 166
movie_id 672 number of ratings 177
movie_id 673 number of ratings 303
movie_id 674 number of ratings 139
movie_id 675 number of ratings 192
movie_id 676 number of ratings 257
movie_id 677 number of ratings 3
movie_id 678 number of ratings 615
movie_id 679 number of ratings 326
movie_id 680 number of ratings 87
movie_id 681 number of ratings 66
movie_id 682 number of ratings 306
movie_id 683 number of ratings 118
movie_id 684 number of ratings 641
movie_id 685 number of ratings 527
movie_id 686 number of ratings 184
movie_id 687 number of ratings 151
movie_id 688 number of ratings 81
movie_id 689 number of ratings 274
movie_id 690 number of ratings 536
movie_id 691 number of ratings 56
movie_id 692 number of ratings 595
movie_id 693 number of ratings 332
movie_id 694 number of ratings 178
movie_id 695 number of ratings 38
movie_id 696 number of ratings 248
movie_id 697 number of ratings 137
movie_id 698 number of ratings 30
movie_id 699 number of ratings 375
movie_id 700 number of ratings 39
movie_id 701 number of ratings 40
movie_id 702 number of ratings 160
movie_id 703 number of ratings 68
movie_id 704 number of ratings 73
movie_id 705 number of ratings 547
movie_id 706 number of ratings 16
movie_id 707 number of ratings 275
movie_id 708 number of ratings 351
movie_id 709 number of ratings 419
movie_id 710 number of ratings 282
movie_id 711 number of ratings 4
movie_id 712 number of ratings 157
movie_id 713 number of ratings 260
movie_id 714 number of ratings 42
movie_id 715 number of ratings 285
movie_id 716 number of ratings 183
movie_id 717 number of ratings 231
movie_id 718 number of ratings 59
movie_id 719 number of ratings 70
movie_id 720 number of ratings 260
movie_id 721 number of ratings 186
movie_id 722 number of ratings 170
movie_id 723 number of ratings 107
movie_id 724 number of ratings 265
movie_id 725 number of ratings 44
movie_id 726 number of ratings 34
movie_id 727 number of ratings 218
movie_id 728 number of ratings 136
movie_id 729 number of ratings 282
movie_id 730 number of ratings 84
movie_id 731 number of ratings 123
movie_id 732 number of ratings 657
movie_id 733 number of ratings 48
movie_id 734 number of ratings 68
movie_id 735 number of ratings 528
movie_id 736 number of ratings 307
movie_id 737 number of ratings 176
movie_id 738 number of ratings 88
movie_id 739 number of ratings 545
movie_id 740 number of ratings 219
movie_id 741 number of ratings 200
movie_id 742 number of ratings 973
movie_id 743 number of ratings 76
movie_id 744 number of ratings 318
movie_id 745 number of ratings 62
movie_id 746 number of ratings 436
movie_id 747 number of ratings 353
movie_id 748 number of ratings 987
movie_id 749 number of ratings 162
movie_id 750 number of ratings 478
movie_id 751 number of ratings 617
movie_id 752 number of ratings 129
movie_id 753 number of ratings 89
movie_id 754 number of ratings 193
movie_id 755 number of ratings 318
movie_id 756 number of ratings 371
movie_id 757 number of ratings 11
movie_id 758 number of ratings 36
movie_id 759 number of ratings 24
movie_id 760 number of ratings 122
movie_id 761 number of ratings 134
movie_id 762 number of ratings 390
movie_id 763 number of ratings 505
movie_id 764 number of ratings 80
movie_id 765 number of ratings 90
movie_id 766 number of ratings 28
movie_id 767 number of ratings 24
movie_id 768 number of ratings 160
movie_id 769 number of ratings 103
movie_id 770 number of ratings 193
movie_id 771 number of ratings 108
movie_id 772 number of ratings 150
movie_id 773 number of ratings 50
movie_id 774 number of ratings 94
movie_id 775 number of ratings 72
movie_id 776 number of ratings 29
movie_id 777 number of ratings 5
movie_id 778 number of ratings 270
movie_id 779 number of ratings 79
movie_id 780 number of ratings 207
movie_id 781 number of ratings 280
movie_id 782 number of ratings 26
movie_id 783 number of ratings 101
movie_id 784 number of ratings 2
movie_id 785 number of ratings 123
movie_id 786 number of ratings 37
movie_id 787 number of ratings 42
movie_id 788 number of ratings 5
movie_id 789 number of ratings 168
movie_id 790 number of ratings 192
movie_id 791 number of ratings 25
movie_id 792 number of ratings 320
movie_id 793 number of ratings 35
movie_id 794 number of ratings 168
movie_id 795 number of ratings 51
movie_id 796 number of ratings 111
movie_id 797 number of ratings 96
movie_id 798 number of ratings 20
movie_id 799 number of ratings 16
movie_id 800 number of ratings 75
movie_id 801 number of ratings 45
movie_id 802 number of ratings 108
movie_id 803 number of ratings 23
movie_id 804 number of ratings 23
movie_id 805 number of ratings 98
movie_id 806 number of ratings 173
movie_id 807 number of ratings 25
movie_id 808 number of ratings 88
movie_id 809 number of ratings 125
movie_id 810 number of ratings 130
movie_id 811 number of ratings 71
movie_id 812 number of ratings 56
movie_id 813 number of ratings 218
movie_id 814 number of ratings 5
movie_id 815 number of ratings 362
movie_id 816 number of ratings 51
movie_id 817 number of ratings 8
movie_id 818 number of ratings 69
movie_id 819 number of ratings 108
movie_id 820 number of ratings 258
movie_id 821 number of ratings 67
movie_id 822 number of ratings 12
movie_id 823 number of ratings 236
movie_id 824 number of ratings 135
movie_id 825 number of ratings 252
movie_id 826 number of ratings 206
movie_id 827 number of ratings 158
movie_id 828 number of ratings 35
movie_id 829 number of ratings 90
movie_id 830 number of ratings 1
movie_id 831 number of ratings 224
movie_id 832 number of ratings 56
movie_id 833 number of ratings 157
movie_id 834 number of ratings 55
movie_id 835 number of ratings 58
movie_id 836 number of ratings 98
movie_id 837 number of ratings 98
movie_id 838 number of ratings 11
movie_id 839 number of ratings 10
movie_id 840 number of ratings 141
movie_id 841 number of ratings 132
movie_id 842 number of ratings 85
movie_id 843 number of ratings 90
movie_id 844 number of ratings 141
movie_id 845 number of ratings 610
movie_id 846 number of ratings 135
movie_id 847 number of ratings 205
movie_id 848 number of ratings 32
movie_id 849 number of ratings 144
movie_id 850 number of ratings 16
movie_id 851 number of ratings 15
movie_id 852 number of ratings 1
movie_id 853 number of ratings 54
movie_id 854 number of ratings 54
movie_id 855 number of ratings 246
movie_id 856 number of ratings 138
movie_id 857 number of ratings 3
movie_id 858 number of ratings 3
movie_id 859 number of ratings 40
movie_id 860 number of ratings 36
movie_id 861 number of ratings 7
movie_id 862 number of ratings 38
movie_id 863 number of ratings 94
movie_id 864 number of ratings 272
movie_id 865 number of ratings 73
movie_id 866 number of ratings 395
movie_id 867 number of ratings 24
movie_id 868 number of ratings 19
movie_id 869 number of ratings 72
movie_id 870 number of ratings 25
movie_id 871 number of ratings 180
movie_id 872 number of ratings 130
movie_id 873 number of ratings 240
movie_id 874 number of ratings 127
movie_id 875 number of ratings 145
movie_id 876 number of ratings 127
movie_id 877 number of ratings 132
movie_id 878 number of ratings 83
movie_id 879 number of ratings 445
movie_id 880 number of ratings 187
movie_id 881 number of ratings 132
movie_id 882 number of ratings 112
movie_id 883 number of ratings 42
movie_id 884 number of ratings 23
movie_id 885 number of ratings 29
movie_id 886 number of ratings 163
movie_id 887 number of ratings 231
movie_id 888 number of ratings 52
movie_id 889 number of ratings 44
movie_id 890 number of ratings 84
movie_id 891 number of ratings 16
movie_id 892 number of ratings 146
movie_id 893 number of ratings 34
movie_id 894 number of ratings 36
movie_id 895 number of ratings 341
movie_id 896 number of ratings 166
movie_id 897 number of ratings 3
movie_id 898 number of ratings 187
movie_id 899 number of ratings 31
movie_id 900 number of ratings 155
movie_id 901 number of ratings 23
movie_id 902 number of ratings 161
movie_id 903 number of ratings 56
movie_id 904 number of ratings 69

movie_id 953 number of ratings 73
movie_id 954 number of ratings 39
movie_id 955 number of ratings 167
movie_id 956 number of ratings 166
movie_id 957 number of ratings 4
movie_id 958 number of ratings 53
movie_id 959 number of ratings 222
movie_id 960 number of ratings 81
movie_id 961 number of ratings 123
movie_id 962 number of ratings 72
movie_id 963 number of ratings 176
movie_id 964 number of ratings 30
movie_id 965 number of ratings 77
movie_id 966 number of ratings 109
movie_id 967 number of ratings 38
movie_id 968 number of ratings 67
movie_id 969 number of ratings 285
movie_id 970 number of ratings 26
movie_id 971 number of ratings 125
movie_id 972 number of ratings 89
movie_id 973 number of ratings 14
movie_id 974 number of ratings 97
movie_id 975 number of ratings 139
movie_id 976 number of ratings 22
movie_id 977 number of ratings 132
movie_id 978 number of ratings 68
movie_id 979 number of ratings 112
movie_id 980 number of ratings 70
movie_id 981 number of ratings 14
movie_id 982 number of ratings 56
movie_id 983 number of ratings 36
movie_id 984 number of ratings 126
movie_id 985 number of ratings 63
movie_id 986 number of ratings 59
movie_id 987 number of ratings 10
movie_id 988 number of ratings 199
movie_id 989 number of ratings 91
movie_id 990 number of ratings 102
movie_id 991 number of ratings 56
movie_id 992 number of ratings 12
movie_id 993 number of ratings 232
movie_id 994 number of ratings 16
movie_id 995 number of ratings 98
movie_id 996 number of ratings 35
movie_id 997 number of ratings 34
movie_id 998 number of ratings 41
movie_id 999 number of ratings 28
movie_id 1000 number of ratings 30
movie_id 1001 number of ratings 34
movie_id 1002 number of ratings 15
movie_id 1003 number of ratings 18
movie_id 1004 number of ratings 28
movie_id 1005 number of ratings 81
movie_id 1006 number of ratings 65
movie_id 1007 number of ratings 194
movie_id 1008 number of ratings 125
movie_id 1009 number of ratings 216
movie_id 1010 number of ratings 143
movie_id 1011 number of ratings 300
movie_id 1012 number of ratings 353
movie_id 1013 number of ratings 87
movie_id 1014 number of ratings 300
movie_id 1015 number of ratings 34
movie_id 1016 number of ratings 474
movie_id 1017 number of ratings 162
movie_id 1018 number of ratings 102
movie_id 1019 number of ratings 123
movie_id 1020 number of ratings 136
movie_id 1021 number of ratings 145
movie_id 1022 number of ratings 110
movie_id 1023 number of ratings 80
movie_id 1024 number of ratings 54
movie_id 1025 number of ratings 129
movie_id 1026 number of ratings 10
movie_id 1027 number of ratings 8
movie_id 1028 number of ratings 450
movie_id 1029 number of ratings 28
movie_id 1030 number of ratings 45
movie_id 1031 number of ratings 16
movie_id 1032 number of ratings 46
movie_id 1033 number of ratings 89
movie_id 1034 number of ratings 68
movie_id 1035 number of ratings 215
movie_id 1036 number of ratings 66
movie_id 1037 number of ratings 48
movie_id 1038 number of ratings 48
movie_id 1039 number of ratings 361
movie_id 1040 number of ratings 65
movie_id 1041 number of ratings 198
movie_id 1042 number of ratings 88
movie_id 1043 number of ratings 24
movie_id 1044 number of ratings 129
movie_id 1045 number of ratings 81
movie_id 1046 number of ratings 146
movie_id 1047 number of ratings 380
movie_id 1048 number of ratings 220
movie_id 1049 number of ratings 63
movie_id 1050 number of ratings 157
movie_id 1051 number of ratings 133
movie_id 1052 number of ratings 57
movie_id 1053 number of ratings 83
movie_id 1054 number of ratings 53
movie_id 1055 number of ratings 32
movie_id 1056 number of ratings 32
movie_id 1057 number of ratings 51
movie_id 1058 number of ratings 49
movie_id 1059 number of ratings 97
movie_id 1060 number of ratings 119
movie_id 1061 number of ratings 85
movie_id 1062 number of ratings 45
movie_id 1063 number of ratings 150
movie_id 1064 number of ratings 17
movie_id 1065 number of ratings 185
movie_id 1066 number of ratings 48
movie_id 1067 number of ratings 152
movie_id 1068 number of ratings 38
movie_id 1069 number of ratings 57
movie_id 1070 number of ratings 101
movie_id 1071 number of ratings 46
movie_id 1072 number of ratings 17
movie_id 1073 number of ratings 252
movie_id 1074 number of ratings 228
movie_id 1075 number of ratings 24
movie_id 1076 number of ratings 27
movie_id 1077 number of ratings 25
movie_id 1078 number of ratings 61
movie_id 1079 number of ratings 101
movie_id 1080 number of ratings 8
movie_id 1081 number of ratings 22
movie_id 1082 number of ratings 21
movie_id 1083 number of ratings 15
movie_id 1084 number of ratings 81
movie_id 1085 number of ratings 33
movie_id 1086 number of ratings 69
movie_id 1087 number of ratings 17
movie_id 1088 number of ratings 29
movie_id 1089 number of ratings 81
movie_id 1090 number of ratings 89
movie_id 1091 number of ratings 117
movie_id 1092 number of ratings 30
movie_id 1093 number of ratings 71
movie_id 1094 number of ratings 29
movie_id 1095 number of ratings 76
movie_id 1096 number of ratings 8
movie_id 1097 number of ratings 63
movie_id 1098 number of ratings 155
movie_id 1099 number of ratings 45
movie_id 1100 number of ratings 21
movie_id 1101 number of ratings 279
movie_id 1102 number of ratings 17
movie_id 1103 number of ratings 72
movie_id 1104 number of ratings 12
movie_id 1105 number of ratings 51
movie_id 1106 number of ratings 12
movie_id 1107 number of ratings 55
movie_id 1108 number of ratings 12
movie_id 1109 number of ratings 96
movie_id 1110 number of ratings 117
movie_id 1111 number of ratings 24
movie_id 1112 number of ratings 42
movie_id 1113 number of ratings 72
movie_id 1114 number of ratings 33
movie_id 1115 number of ratings 99
movie_id 1116 number of ratings 47
movie_id 1117 number of ratings 59
movie_id 1118 number of ratings 153
movie_id 1119 number of ratings 216
movie_id 1120 number of ratings 51
movie_id 1121 number of ratings 79
movie_id 1122 number of ratings 5
movie_id 1123 number of ratings 11
movie_id 1124 number of ratings 46
movie_id 1125 number of ratings 17
movie_id 1126 number of ratings 107
movie_id 1127 number of ratings 32
movie_id 1128 number of ratings 35
movie_id 1129 number of ratings 100
movie_id 1130 number of ratings 4
movie_id 1131 number of ratings 52
movie_id 1132 number of ratings 84
movie_id 1133 number of ratings 89
movie_id 1134 number of ratings 126
movie_id 1135 number of ratings 137
movie_id 1136 number of ratings 101
movie_id 1137 number of ratings 115
movie_id 1138 number of ratings 17
movie_id 1139 number of ratings 86
movie_id 1140 number of ratings 39
movie_id 1141 number of ratings 30
movie_id 1142 number of ratings 178
movie_id 1143 number of ratings 60
movie_id 1144 number of ratings 11
movie_id 1145 number of ratings 24
movie_id 1146 number of ratings 6
movie_id 1147 number of ratings 77
movie_id 1148 number of ratings 30
movie_id 1149 number of ratings 100
movie_id 1150 number of ratings 28
movie_id 1151 number of ratings 15
movie_id 1152 number of ratings 96
movie_id 1153 number of ratings 66
movie_id 1154 number of ratings 40
movie_id 1155 number of ratings 10
movie_id 1156 number of ratings 3
movie_id 1157 number of ratings 72
movie_id 1158 number of ratings 16
movie_id 1159 number of ratings 39
movie_id 1160 number of ratings 94
movie_id 1161 number of ratings 38
movie_id 1162 number of ratings 8
movie_id 1163 number of ratings 67
movie_id 1164 number of ratings 13
movie_id 1165 number of ratings 26
movie_id 1166 number of ratings 38
movie_id 1167 number of ratings 39
movie_id 1168 number of ratings 73
movie_id 1169 number of ratings 41
movie_id 1170 number of ratings 83
movie_id 1171 number of ratings 44
movie_id 1172 number of ratings 55
movie_id 1173 number of ratings 18
movie_id 1174 number of ratings 26
movie_id 1175 number of ratings 17
movie_id 1176 number of ratings 74
movie_id 1177 number of ratings 13
movie_id 1178 number of ratings 47
movie_id 1179 number of ratings 19
movie_id 1180 number of ratings 25
movie_id 1181 number of ratings 25
movie_id 1182 number of ratings 30
movie_id 1183 number of ratings 42
movie_id 1184 number of ratings 25
movie_id 1185 number of ratings 41
movie_id 1186 number of ratings 10
movie_id 1187 number of ratings 42
movie_id 1188 number of ratings 122
movie_id 1189 number of ratings 15
movie_id 1190 number of ratings 37
movie_id 1191 number of ratings 13
movie_id 1192 number of ratings 44
movie_id 1193 number of ratings 38
movie_id 1194 number of ratings 126
movie_id 1195 number of ratings 36
movie_id 1196 number of ratings 9
movie_id 1197 number of ratings 160
movie_id 1198 number of ratings 22
movie_id 1199 number of ratings 66
movie_id 1200 number of ratings 23
movie_id 1201 number of ratings 5
movie_id 1202 number of ratings 28
movie_id 1203 number of ratings 85
movie_id 1204 number of ratings 65
movie_id 1205 number of ratings 18
movie_id 1206 number of ratings 51
movie_id 1207 number of ratings 39
movie_id 1208 number of ratings 57
movie_id 1209 number of ratings 38
movie_id 1210 number of ratings 104
movie_id 1211 number of ratings 41
movie_id 1212 number of ratings 17
movie_id 1213 number of ratings 13
movie_id 1214 number of ratings 18
movie_id 1215 number of ratings 58
movie_id 1216 number of ratings 18
movie_id 1217 number of ratings 112
movie_id 1218 number of ratings 90
movie_id 1219 number of ratings 58
movie_id 1220 number of ratings 100
movie_id 1221 number of ratings 136
movie_id 1222 number of ratings 67
movie_id 1223 number of ratings 14
movie_id 1224 number of ratings 32
movie_id 1225 number of ratings 37
movie_id 1226 number of ratings 108
movie_id 1227 number of ratings 19
movie_id 1228 number of ratings 118
movie_id 1229 number of ratings 28
movie_id 1230 number of ratings 33
movie_id 1231 number of ratings 55
movie_id 1232 number of ratings 42
movie_id 1233 number of ratings 21
movie_id 1234 number of ratings 19
movie_id 1235 number of ratings 4
movie_id 1236 number of ratings 3
movie_id 1237 number of ratings 21
movie_id 1238 number of ratings 25
movie_id 1239 number of ratings 44
movie_id 1240 number of ratings 95
movie_id 1241 number of ratings 16
movie_id 1242 number of ratings 13
movie_id 1243 number of ratings 26
movie_id 1244 number of ratings 105
movie_id 1245 number of ratings 61
movie_id 1246 number of ratings 11
movie_id 1247 number of ratings 11
movie_id 1248 number of ratings 57
movie_id 1249 number of ratings 34
movie_id 1250 number of ratings 9
movie_id 1251 number of ratings 33
movie_id 1252 number of ratings 27
movie_id 1253 number of ratings 17
movie_id 1254 number of ratings 20
movie_id 1255 number of ratings 18
movie_id 1256 number of ratings 6
movie_id 1257 number of ratings 7
movie_id 1258 number of ratings 58
movie_id 1259 number of ratings 8
movie_id 1260 number of ratings 11
movie_id 1261 number of ratings 13
movie_id 1262 number of ratings 29
movie_id 1263 number of ratings 44
movie_id 1264 number of ratings 23
movie_id 1265 number of ratings 58
movie_id 1266 number of ratings 38
movie_id 1267 number of ratings 99
movie_id 1268 number of ratings 33
movie_id 1269 number of ratings 39
movie_id 1270 number of ratings 16
movie_id 1271 number of ratings 19
movie_id 1272 number of ratings 9
movie_id 1273 number of ratings 41
movie_id 1274 number of ratings 19
movie_id 1275 number of ratings 10
movie_id 1276 number of ratings 20
movie_id 1277 number of ratings 65
movie_id 1278 number of ratings 58
movie_id 1279 number of ratings 26
movie_id 1280 number of ratings 43
movie_id 1281 number of ratings 41
movie_id 1282 number of ratings 29
movie_id 1283 number of ratings 51
movie_id 1284 number of ratings 74
movie_id 1285 number of ratings 47
movie_id 1286 number of ratings 63
movie_id 1287 number of ratings 8
movie_id 1288 number of ratings 21
movie_id 1289 number of ratings 15
movie_id 1290 number of ratings 3
movie_id 1291 number of ratings 33
movie_id 1292 number of ratings 5
movie_id 1293 number of ratings 15
movie_id 1294 number of ratings 22
movie_id 1295 number of ratings 18
movie_id 1296 number of ratings 65
movie_id 1297 number of ratings 34
movie_id 1298 number of ratings 33
movie_id 1299 number of ratings 24
movie_id 1300 number of ratings 21
movie_id 1301 number of ratings 19
movie_id 1302 number of ratings 17
movie_id 1303 number of ratings 42
movie_id 1304 number of ratings 5
movie_id 1305 number of ratings 17
movie_id 1306 number of ratings 6
movie_id 1307 number of ratings 3
movie_id 1308 number of ratings 2
movie_id 1309 number of ratings 1
movie_id 1310 number of ratings 3
movie_id 1311 number of ratings 40
movie_id 1312 number of ratings 21
movie_id 1313 number of ratings 44
movie_id 1314 number of ratings 27
movie_id 1315 number of ratings 72
movie_id 1316 number of ratings 19
movie_id 1317 number of ratings 8
movie_id 1318 number of ratings 4
movie_id 1319 number of ratings 7
movie_id 1320 number of ratings 1
movie_id 1321 number of ratings 5
movie_id 1322 number of ratings 14
movie_id 1323 number of ratings 8
movie_id 1324 number of ratings 12
movie_id 1325 number of ratings 1
movie_id 1326 number of ratings 20
movie_id 1327 number of ratings 7
movie_id 1328 number of ratings 19
movie_id 1329 number of ratings 1
movie_id 1330 number of ratings 10
movie_id 1331 number of ratings 12
movie_id 1332 number of ratings 4
movie_id 1333 number of ratings 14
movie_id 1334 number of ratings 2
movie_id 1335 number of ratings 29
movie_id 1336 number of ratings 18
movie_id 1337 number of ratings 21
movie_id 1338 number of ratings 9
movie_id 1339 number of ratings 1
movie_id 1340 number of ratings 1
movie_id 1341 number of ratings 1
movie_id 1342 number of ratings 5
movie_id 1343 number of ratings 1
movie_id 1344 number of ratings 16
movie_id 1345 number of ratings 4
movie_id 1346 number of ratings 12
movie_id 1347 number of ratings 11
movie_id 1348 number of ratings 1
movie_id 1349 number of ratings 1
movie_id 1350 number of ratings 3
movie_id 1351 number of ratings 6
movie_id 1352 number of ratings 1
movie_id 1353 number of ratings 13
movie_id 1354 number of ratings 2
movie_id 1355 number of ratings 16
movie_id 1356 number of ratings 8
movie_id 1357 number of ratings 8
movie_id 1358 number of ratings 6
movie_id 1359 number of ratings 2
movie_id 1360 number of ratings 3
movie_id 1361 number of ratings 8
movie_id 1362 number of ratings 4
movie_id 1363 number of ratings 1
movie_id 1364 number of ratings 1
movie_id 1365 number of ratings 3
movie_id 1366 number of ratings 1
movie_id 1367 number of ratings 21
movie_id 1368 number of ratings 22
movie_id 1369 number of ratings 11
movie_id 1370 number of ratings 8
movie_id 1371 number of ratings 3
movie_id 1372 number of ratings 9
movie_id 1373 number of ratings 1
movie_id 1374 number of ratings 2
movie_id 1375 number of ratings 36
movie_id 1376 number of ratings 15
movie_id 1377 number of ratings 13
movie_id 1378 number of ratings 11
movie_id 1379 number of ratings 20
movie_id 1380 number of ratings 14
movie_id 1381 number of ratings 26
movie_id 1382 number of ratings 8
movie_id 1383 number of ratings 12
movie_id 1384 number of ratings 5
movie_id 1385 number of ratings 14
movie_id 1386 number of ratings 16
movie_id 1387 number of ratings 6
movie_id 1388 number of ratings 20
movie_id 1389 number of ratings 9
movie_id 1390 number of ratings 4
movie_id 1391 number of ratings 6
movie_id 1392 number of ratings 10
movie_id 1393 number of ratings 19
movie_id 1394 number of ratings 17
movie_id 1395 number of ratings 14
movie_id 1396 number of ratings 21
movie_id 1397 number of ratings 16
movie_id 1398 number of ratings 9
movie_id 1399 number of ratings 17
movie_id 1400 number of ratings 31
movie_id 1401 number of ratings 58
movie_id 1402 number of ratings 11
movie_id 1403 number of ratings 11
movie_id 1404 number of ratings 42
movie_id 1405 number of ratings 20
movie_id 1406 number of ratings 17
movie_id 1407 number of ratings 45
movie_id 1408 number of ratings 3
movie_id 1409 number of ratings 20
movie_id 1410 number of ratings 11
movie_id 1411 number of ratings 72
movie_id 1412 number of ratings 10
movie_id 1413 number of ratings 22
movie_id 1414 number of ratings 2
movie_id 1415 number of ratings 22
movie_id 1416 number of ratings 12
movie_id 1417 number of ratings 5
movie_id 1418 number of ratings 11
movie_id 1419 number of ratings 34
movie_id 1420 number of ratings 4
movie_id 1421 number of ratings 35
movie_id 1422 number of ratings 9
movie_id 1423 number of ratings 9
movie_id 1424 number of ratings 7
movie_id 1425 number of ratings 26
movie_id 1426 number of ratings 26
movie_id 1427 number of ratings 14
movie_id 1428 number of ratings 44
movie_id 1429 number of ratings 11
movie_id 1430 number of ratings 7
movie_id 1431 number of ratings 17
movie_id 1432 number of ratings 3
movie_id 1433 number of ratings 4
movie_id 1434 number of ratings 25
movie_id 1435 number of ratings 18
movie_id 1436 number of ratings 5
movie_id 1437 number of ratings 18
movie_id 1438 number of ratings 12
movie_id 1439 number of ratings 24
movie_id 1440 number of ratings 15
movie_id 1441 number of ratings 18
movie_id 1442 number of ratings 12
movie_id 1443 number of ratings 15
movie_id 1444 number of ratings 47
movie_id 1445 number of ratings 11
movie_id 1446 number of ratings 47
movie_id 1447 number of ratings 3
movie_id 1448 number of ratings 11
movie_id 1449 number of ratings 37
movie_id 1450 number of ratings 8
movie_id 1451 number of ratings 58
movie_id 1452 number of ratings 4
movie_id 1453 number of ratings 2
movie_id 1454 number of ratings 18
movie_id 1455 number of ratings 5
movie_id 1456 number of ratings 26
movie_id 1457 number of ratings 3
movie_id 1458 number of ratings 4
movie_id 1459 number of ratings 25
movie_id 1460 number of ratings 3
movie_id 1461 number of ratings 2
movie_id 1462 number of ratings 26
movie_id 1463 number of ratings 10
movie_id 1464 number of ratings 7
movie_id 1465 number of ratings 7
movie_id 1466 number of ratings 24
movie_id 1467 number of ratings 10
movie_id 1468 number of ratings 20
movie_id 1469 number of ratings 38
movie_id 1470 number of ratings 13
movie_id 1471 number of ratings 22
movie_id 1472 number of ratings 7
movie_id 1473 number of ratings 32
movie_id 1474 number of ratings 17
movie_id 1475 number of ratings 23
movie_id 1476 number of ratings 2
movie_id 1477 number of ratings 5
movie_id 1478 number of ratings 49
movie_id 1479 number of ratings 22
movie_id 1480 number of ratings 25
movie_id 1481 number of ratings 6
movie_id 1482 number of ratings 4
movie_id 1483 number of ratings 41
movie_id 1484 number of ratings 8
movie_id 1485 number of ratings 14
movie_id 1486 number of ratings 1
movie_id 1487 number of ratings 10
movie_id 1488 number of ratings 12
movie_id 1489 number of ratings 11
movie_id 1490 number of ratings 9
movie_id 1491 number of ratings 6
movie_id 1492 number of ratings 4
movie_id 1493 number of ratings 1
movie_id 1494 number of ratings 1
movie_id 1495 number of ratings 18
movie_id 1496 number of ratings 14
movie_id 1497 number of ratings 6
movie_id 1498 number of ratings 4
movie_id 1499 number of ratings 13
movie_id 1500 number of ratings 10
movie_id 1501 number of ratings 15
movie_id 1502 number of ratings 3
movie_id 1503 number of ratings 31
movie_id 1504 number of ratings 11
movie_id 1505 number of ratings 4
movie_id 1506 number of ratings 11
movie_id 1507 number of ratings 3
movie_id 1508 number of ratings 7
movie_id 1509 number of ratings 8
movie_id 1510 number of ratings 3
movie_id 1511 number of ratings 16
movie_id 1512 number of ratings 24
movie_id 1513 number of ratings 6
movie_id 1514 number of ratings 22
movie_id 1515 number of ratings 4
movie_id 1516 number of ratings 12
movie_id 1517 number of ratings 14
movie_id 1518 number of ratings 36
movie_id 1519 number of ratings 6
movie_id 1520 number of ratings 3
movie_id 1521 number of ratings 12
movie_id 1522 number of ratings 17
movie_id 1523 number of ratings 6
movie_id 1524 number of ratings 34
movie_id 1525 number of ratings 4
movie_id 1526 number of ratings 4

movie_id 1578 number of ratings 4
movie_id 1579 number of ratings 1
movie_id 1580 number of ratings 1
movie_id 1581 number of ratings 1
movie_id 1582 number of ratings 1
movie_id 1583 number of ratings 1
movie_id 1584 number of ratings 1
movie_id 1585 number of ratings 5
movie_id 1586 number of ratings 1
movie_id 1587 number of ratings 1
movie_id 1588 number of ratings 4
movie_id 1589 number of ratings 12
movie_id 1590 number of ratings 4
movie_id 1591 number of ratings 19
movie_id 1592 number of ratings 18
movie_id 1593 number of ratings 4
movie_id 1594 number of ratings 9
movie_id 1595 number of ratings 2
movie_id 1596 number of ratings 2
movie_id 1597 number of ratings 15
movie_id 1598 number of ratings 15
movie_id 1599 number of ratings 5
movie_id 1600 number of ratings 15
movie_id 1601 number of ratings 1
movie_id 1602 number of ratings 10
movie_id 1603 number of ratings 3
movie_id 1604 number of ratings 4
movie_id 1605 number of ratings 12
movie_id 1606 number of ratings 2
movie_id 1607 number of ratings 10
movie_id 1608 number of ratings 9
movie_id 1609 number of ratings 5
movie_id 1610 number of ratings 6
movie_id 1611 number of ratings 6
movie_id 1612 number of ratings 15
movie_id 1613 number of ratings 4
movie_id 1614 number of ratings 3
movie_id 1615 number of ratings 30
movie_id 1616 number of ratings 4
movie_id 1617 number of ratings 6
movie_id 1618 number of ratings 1
movie_id 1619 number of ratings 3
movie_id 1620 number of ratings 29
movie_id 1621 number of ratings 1
movie_id 1622 number of ratings 7
movie_id 1623 number of ratings 12
movie_id 1624 number of ratings 2
movie_id 1625 number of ratings 4
movie_id 1626 number of ratings 1
movie_id 1627 number of ratings 3
movie_id 1628 number of ratings 15
movie_id 1629 number of ratings 8
movie_id 1630 number of ratings 3
movie_id 1631 number of ratings 7
movie_id 1632 number of ratings 3
movie_id 1633 number of ratings 3
movie_id 1634 number of ratings 2
movie_id 1635 number of ratings 3
movie_id 1636 number of ratings 4
movie_id 1637 number of ratings 3
movie_id 1638 number of ratings 3
movie_id 1639 number of ratings 13
movie_id 1640 number of ratings 3
movie_id 1641 number of ratings 3
movie_id 1642 number of ratings 9
movie_id 1643 number of ratings 15
movie_id 1644 number of ratings 3
movie_id 1645 number of ratings 4
movie_id 1646 number of ratings 7
movie_id 1647 number of ratings 3
movie_id 1648 number of ratings 2
movie_id 1649 number of ratings 3
movie_id 1650 number of ratings 4
movie_id 1651 number of ratings 4
movie_id 1652 number of ratings 5
movie_id 1653 number of ratings 5
movie_id 1654 number of ratings 1
movie_id 1655 number of ratings 2
movie_id 1656 number of ratings 7
movie_id 1657 number of ratings 3
movie_id 1658 number of ratings 9
movie_id 1659 number of ratings 1
movie_id 1660 number of ratings 2
movie_id 1661 number of ratings 1
movie_id 1662 number of ratings 5
movie_id 1663 number of ratings 2
movie_id 1664 number of ratings 13
movie_id 1665 number of ratings 2
movie_id 1666 number of ratings 2
movie_id 1667 number of ratings 3
movie_id 1668 number of ratings 3
movie_id 1669 number of ratings 2
movie_id 1670 number of ratings 3
movie_id 1671 number of ratings 1
movie_id 1672 number of ratings 4
movie_id 1673 number of ratings 3
movie_id 1674 number of ratings 4
movie_id 1675 number of ratings 3
movie_id 1676 number of ratings 2
movie_id 1677 number of ratings 3
movie_id 1678 number of ratings 1
movie_id 1679 number of ratings 3
movie_id 1680 number of ratings 2
movie_id 1681 number of ratings 3
movie_id 1682 number of ratings 3

**Question 3**:
* get the average rating per user
* list all occupations and if they are male or female dominant

In [295]:
# get the average rating per user
user_id_and_rating = ['user_id', 'rating']
b = ratings[user_id_and_rating]
sorted_user_id = b.sort_values(by=['user_id'])
user_means = np.array([])
for i in range(1,944):
    mean = np.mean(sorted_user_id[sorted_user_id.user_id == i].rating)
    user_means = np.append(user_means, mean)
for i, rat in enumerate(user_means, 1):
    print("user id = ", i," rating =", rat)


# list all occupations and if they are male or female dominant
occ = users["occupation"].unique()
f = 0
m = 0
print("Occupations = ", users["occupation"].unique()) # this prints all of the different types of occupations
for i in occ:
    m = users[(users.sex == "M") & (users.occupation == i)].user_id.count()
    f = users[(users.sex == "F") & (users.occupation == i)].user_id.count()
    if m > f: 
        print("males are more dominant in ", i)
    elif m < f:
        print("females are more dominant in ", i)
    else:
        print("equal domination of both genders")

print('number of male users: ')
print(sum(users["sex"] == "M"))

print('number of female users: ')
print(sum(users['sex'] == 'F'))

user id =  1  rating = 3.610294117647059
user id =  2  rating = 3.7096774193548385
user id =  3  rating = 2.7962962962962963
user id =  4  rating = 4.333333333333333
user id =  5  rating = 2.874285714285714
user id =  6  rating = 3.6350710900473935
user id =  7  rating = 3.965260545905707
user id =  8  rating = 3.7966101694915255
user id =  9  rating = 4.2727272727272725
user id =  10  rating = 4.206521739130435
user id =  11  rating = 3.4640883977900554
user id =  12  rating = 4.392156862745098
user id =  13  rating = 3.09748427672956
user id =  14  rating = 4.091836734693878
user id =  15  rating = 2.875
user id =  16  rating = 4.328571428571428
user id =  17  rating = 3.0357142857142856
user id =  18  rating = 3.88086642599278
user id =  19  rating = 3.55
user id =  20  rating = 3.1041666666666665
user id =  21  rating = 2.670391061452514
user id =  22  rating = 3.3515625
user id =  23  rating = 3.6357615894039736
user id =  24  rating = 4.323529411764706
user id =  25  rating = 4.051282051282051
user id =  26  rating = 2.94392523364486
user id =  27  rating = 3.24
user id =  28  rating = 3.721518987341772
user id =  29  rating = 3.6470588235294117
user id =  30  rating = 3.7674418604651163
user id =  31  rating = 3.9166666666666665
user id =  32  rating = 3.317073170731707
user id =  33  rating = 3.7083333333333335
user id =  34  rating = 4.05
user id =  35  rating = 3.0
user id =  36  rating = 3.8
user id =  37  rating = 3.6491228070175437
user id =  38  rating = 3.71900826446281
user id =  39  rating = 3.772727272727273
user id =  40  rating = 2.8857142857142857
user id =  41  rating = 3.769230769230769
user id =  42  rating = 3.726775956284153
user id =  43  rating = 3.7104072398190047
user id =  44  rating = 3.6490066225165565
user id =  45  rating = 3.6041666666666665
user id =  46  rating = 4.111111111111111
user id =  47  rating = 3.64
user id =  48  rating = 3.787878787878788
user id =  49  rating = 2.683720930232558
user id =  50  rating = 3.5416666666666665
user id =  51  rating = 3.5652173913043477
user id =  52  rating = 4.267857142857143
user id =  53  rating = 3.8214285714285716
user id =  54  rating = 3.6923076923076925
user id =  55  rating = 3.2857142857142856
user id =  56  rating = 3.641711229946524
user id =  57  rating = 3.5
user id =  58  rating = 3.8376623376623376
user id =  59  rating = 3.9345549738219896
user id =  60  rating = 4.086538461538462
user id =  61  rating = 2.9523809523809526
user id =  62  rating = 3.3017241379310347
user id =  63  rating = 3.118279569892473
user id =  64  rating = 3.585
user id =  65  rating = 3.9375
user id =  66  rating = 3.473684210526316
user id =  67  rating = 3.7666666666666666
user id =  68  rating = 3.0294117647058822
user id =  69  rating = 3.8461538461538463
user id =  70  rating = 3.4656488549618323
user id =  71  rating = 3.789473684210526
user id =  72  rating = 3.8175182481751824
user id =  73  rating = 3.727272727272727
user id =  74  rating = 3.641025641025641
user id =  75  rating = 3.278481012658228
user id =  76  rating = 3.5609756097560976
user id =  77  rating = 3.611111111111111
user id =  78  rating = 3.380952380952381
user id =  79  rating = 4.0
user id =  80  rating = 3.7586206896551726
user id =  81  rating = 3.293103448275862
user id =  82  rating = 3.0714285714285716
user id =  83  rating = 3.4193548387096775
user id =  84  rating = 3.8529411764705883
user id =  85  rating = 3.5381944444444446
user id =  86  rating = 3.5217391304347827
user id =  87  rating = 3.7914691943127963
user id =  88  rating = 3.9523809523809526
user id =  89  rating = 4.0394736842105265
user id =  90  rating = 4.223333333333334
user id =  91  rating = 3.8877551020408165
user id =  92  rating = 3.2448453608247423
user id =  93  rating = 3.35
user id =  94  rating = 3.6575
user id =  95  rating = 3.41726618705036
user id =  96  rating = 4.267857142857143
user id =  97  rating = 4.158730158730159
user id =  98  rating = 3.5925925925925926
user id =  99  rating = 3.551470588235294
user id =  100  rating = 3.0677966101694913
user id =  101  rating = 2.8955223880597014
user id =  102  rating = 2.615740740740741
user id =  103  rating = 3.6206896551724137
user id =  104  rating = 2.6666666666666665
user id =  105  rating = 3.391304347826087
user id =  106  rating = 3.765625
user id =  107  rating = 3.0
user id =  108  rating = 3.5757575757575757
user id =  109  rating = 3.4401709401709404
user id =  110  rating = 3.045112781954887
user id =  111  rating = 3.5416666666666665
user id =  112  rating = 3.6956521739130435
user id =  113  rating = 3.7254901960784315
user id =  114  rating = 3.6041666666666665
user id =  115  rating = 3.9347826086956523
user id =  116  rating = 3.006993006993007
user id =  117  rating = 3.9186046511627906
user id =  118  rating = 4.661971830985915
user id =  119  rating = 3.9502762430939224
user id =  120  rating = 3.576923076923077
user id =  121  rating = 3.608108108108108
user id =  122  rating = 3.9836065573770494
user id =  123  rating = 3.8518518518518516
user id =  124  rating = 3.5
user id =  125  rating = 3.4395604395604398
user id =  126  rating = 3.533333333333333
user id =  127  rating = 4.130434782608695
user id =  128  rating = 3.6630434782608696
user id =  129  rating = 2.6
user id =  130  rating = 3.9858356940509916
user id =  131  rating = 4.133333333333334
user id =  132  rating = 3.772727272727273
user id =  133  rating = 3.1923076923076925
user id =  134  rating = 3.64
user id =  135  rating = 3.381818181818182
user id =  136  rating = 4.3428571428571425
user id =  137  rating = 4.319148936170213
user id =  138  rating = 4.2745098039215685
user id =  139  rating = 4.0
user id =  140  rating = 3.4285714285714284
user id =  141  rating = 3.4299065420560746
user id =  142  rating = 3.6363636363636362
user id =  143  rating = 3.9
user id =  144  rating = 3.674757281553398
user id =  145  rating = 3.3354430379746836
user id =  146  rating = 3.6206896551724137
user id =  147  rating = 4.2
user id =  148  rating = 4.0
user id =  149  rating = 2.888888888888889
user id =  150  rating = 3.84375
user id =  151  rating = 3.996742671009772
user id =  152  rating = 4.320754716981132
user id =  153  rating = 2.9565217391304346
user id =  154  rating = 3.9607843137254903
user id =  155  rating = 2.6363636363636362
user id =  156  rating = 3.72972972972973
user id =  157  rating = 3.784313725490196
user id =  158  rating = 3.8034682080924855
user id =  159  rating = 3.4299065420560746
user id =  160  rating = 3.9166666666666665
user id =  161  rating = 2.5517241379310347
user id =  162  rating = 3.5952380952380953
user id =  163  rating = 3.3043478260869565
user id =  164  rating = 4.126984126984127
user id =  165  rating = 4.0
user id =  166  rating = 3.55
user id =  167  rating = 3.3768115942028984
user id =  168  rating = 3.3333333333333335
user id =  169  rating = 3.972972972972973
user id =  170  rating = 3.772727272727273
user id =  171  rating = 3.4642857142857144
user id =  172  rating = 3.185185185185185
user id =  173  rating = 4.209302325581396
user id =  174  rating = 3.5819209039548023
user id =  175  rating = 3.736842105263158
user id =  176  rating = 3.6984126984126986
user id =  177  rating = 3.617391304347826
user id =  178  rating = 3.681318681318681
user id =  179  rating = 3.0476190476190474
user id =  180  rating = 3.9365079365079363
user id =  181  rating = 1.4919540229885058
user id =  182  rating = 3.857142857142857
user id =  183  rating = 3.188679245283019
user id =  184  rating = 3.6613545816733066
user id =  185  rating = 4.041666666666667
user id =  186  rating = 3.4130434782608696
user id =  187  rating = 4.071428571428571
user id =  188  rating = 3.767857142857143
user id =  189  rating = 3.978609625668449
user id =  190  rating = 3.3220338983050848
user id =  191  rating = 3.6296296296296298
user id =  192  rating = 3.5142857142857142
user id =  193  rating = 3.165289256198347
user id =  194  rating = 2.963934426229508
user id =  195  rating = 3.2916666666666665
user id =  196  rating = 3.6153846153846154
user id =  197  rating = 3.3389830508474576
user id =  198  rating = 3.276243093922652
user id =  199  rating = 2.95
user id =  200  rating = 4.032407407407407
user id =  201  rating = 3.0310880829015545
user id =  202  rating = 2.8
user id =  203  rating = 3.4186046511627906
user id =  204  rating = 3.4523809523809526
user id =  205  rating = 2.8636363636363638
user id =  206  rating = 2.171875
user id =  207  rating = 3.2304347826086954
user id =  208  rating = 3.787878787878788
user id =  209  rating = 3.1818181818181817
user id =  210  rating = 4.0606060606060606
user id =  211  rating = 3.189189189189189
user id =  212  rating = 3.92
user id =  213  rating = 4.23015873015873
user id =  214  rating = 3.8984375
user id =  215  rating = 3.774193548387097
user id =  216  rating = 3.801526717557252
user id =  217  rating = 2.960526315789474
user id =  218  rating = 3.6037735849056602
user id =  219  rating = 3.7142857142857144
user id =  220  rating = 3.772727272727273
user id =  221  rating = 3.6164383561643834
user id =  222  rating = 3.049095607235142
user id =  223  rating = 3.0285714285714285
user id =  224  rating = 2.99290780141844
user id =  225  rating = 4.518518518518518
user id =  226  rating = 3.8
user id =  227  rating = 3.4482758620689653
user id =  228  rating = 3.142857142857143
user id =  229  rating = 2.7333333333333334
user id =  230  rating = 3.8496240601503757
user id =  231  rating = 3.6666666666666665
user id =  232  rating = 3.903225806451613
user id =  233  rating = 4.345454545454546
user id =  234  rating = 3.122916666666667
user id =  235  rating = 3.978723404255319
user id =  236  rating = 3.475806451612903
user id =  237  rating = 4.145833333333333
user id =  238  rating = 3.2758620689655173
user id =  239  rating = 4.213836477987422
user id =  240  rating = 3.75
user id =  241  rating = 3.4347826086956523
user id =  242  rating = 4.45
user id =  243  rating = 3.6419753086419755
user id =  244  rating = 3.6512605042016806
user id =  245  rating = 3.272727272727273
user id =  246  rating = 2.928205128205128
user id =  247  rating = 3.923076923076923
user id =  248  rating = 3.5714285714285716
user id =  249  rating = 4.105590062111801
user id =  250  rating = 3.7868852459016393
user id =  251  rating = 3.792207792207792
user id =  252  rating = 4.428571428571429
user id =  253  rating = 3.979381443298969
user id =  254  rating = 3.050314465408805
user id =  255  rating = 2.5421686746987953
user id =  256  rating = 3.9903381642512077
user id =  257  rating = 4.035087719298246
user id =  258  rating = 3.739130434782609
user id =  259  rating = 3.869565217391304
user id =  260  rating = 4.041666666666667
user id =  261  rating = 4.111111111111111
user id =  262  rating = 3.16875
user id =  263  rating = 4.048780487804878
user id =  264  rating = 4.216666666666667
user id =  265  rating = 3.5652173913043477
user id =  266  rating = 3.260869565217391
user id =  267  rating = 3.9351351351351354
user id =  268  rating = 2.942073170731707
user id =  269  rating = 3.0092879256965945
user id =  270  rating = 4.333333333333333
user id =  271  rating = 3.58273381294964
user id =  272  rating = 4.333333333333333
user id =  273  rating = 3.6363636363636362
user id =  274  rating = 4.056338028169014
user id =  275  rating = 3.1157894736842104
user id =  276  rating = 3.465250965250965
user id =  277  rating = 3.5
user id =  278  rating = 4.260869565217392
user id =  279  rating = 3.2672811059907834
user id =  280  rating = 3.5775193798449614
user id =  281  rating = 3.1923076923076925
user id =  282  rating = 3.5
user id =  283  rating = 4.132075471698113
user id =  284  rating = 3.5531914893617023
user id =  285  rating = 3.9375
user id =  286  rating = 3.7118055555555554
user id =  287  rating = 4.112903225806452
user id =  288  rating = 3.88
user id =  289  rating = 2.925925925925926
user id =  290  rating = 3.3533333333333335
user id =  291  rating = 3.685810810810811
user id =  292  rating = 4.225806451612903
user id =  293  rating = 3.0309278350515463
user id =  294  rating = 3.466666666666667
user id =  295  rating = 4.239795918367347
user id =  296  rating = 4.1768707482993195
user id =  297  rating = 3.4375
user id =  298  rating = 4.031496062992126
user id =  299  rating = 3.4642857142857144
user id =  300  rating = 3.75
user id =  301  rating = 3.5272727272727273
user id =  302  rating = 2.4285714285714284
user id =  303  rating = 3.365702479338843
user id =  304  rating = 3.3846153846153846
user id =  305  rating = 3.40990990990991
user id =  306  rating = 3.78125
user id =  307  rating = 3.794642857142857
user id =  308  rating = 3.7581863979848866
user id =  309  rating = 3.5
user id =  310  rating = 3.857142857142857
user id =  311  rating = 3.795918367346939
user id =  312  rating = 4.381165919282512
user id =  313  rating = 3.595419847328244
user id =  314  rating = 3.6775510204081634
user id =  315  rating = 4.011494252873563
user id =  316  rating = 3.36
user id =  317  rating = 3.5454545454545454
user id =  318  rating = 3.706896551724138
user id =  319  rating = 3.4782608695652173
user id =  320  rating = 3.720779220779221
user id =  321  rating = 3.736
user id =  322  rating = 4.176470588235294
user id =  323  rating = 3.6179775280898876
user id =  324  rating = 4.348484848484849
user id =  325  rating = 3.408450704225352
user id =  326  rating = 3.3262032085561497
user id =  327  rating = 3.313380281690141
user id =  328  rating = 3.431095406360424
user id =  329  rating = 3.4
user id =  330  rating = 4.496598639455782
user id =  331  rating = 3.642857142857143
user id =  332  rating = 4.1530054644808745
user id =  333  rating = 3.8461538461538463
user id =  334  rating = 3.5195195195195197
user id =  335  rating = 3.5454545454545454
user id =  336  rating = 2.9615384615384617
user id =  337  rating = 3.9411764705882355
user id =  338  rating = 4.0
user id =  339  rating = 4.003937007874016
user id =  340  rating = 4.159090909090909
user id =  341  rating = 3.8095238095238093
user id =  342  rating = 3.4378109452736316
user id =  343  rating = 3.9873417721518987
user id =  344  rating = 3.668421052631579
user id =  345  rating = 3.646551724137931
user id =  346  rating = 3.290155440414508
user id =  347  rating = 3.5728643216080402
user id =  348  rating = 3.896551724137931
user id =  349  rating = 3.1951219512195124
user id =  350  rating = 4.32
user id =  351  rating = 4.159090909090909
user id =  352  rating = 3.738095238095238
user id =  353  rating = 3.36
user id =  354  rating = 3.742489270386266
user id =  355  rating = 4.076923076923077
user id =  356  rating = 3.5833333333333335
user id =  357  rating = 4.131578947368421
user id =  358  rating = 3.697674418604651
user id =  359  rating = 3.925925925925926
user id =  360  rating = 3.9607843137254903
user id =  361  rating = 3.7768595041322315
user id =  362  rating = 3.36
user id =  363  rating = 3.054662379421222
user id =  364  rating = 3.45
user id =  365  rating = 3.3793103448275863
user id =  366  rating = 4.393939393939394
user id =  367  rating = 4.155172413793103
user id =  368  rating = 3.2888888888888888
user id =  369  rating = 4.0
user id =  370  rating = 3.6933333333333334
user id =  371  rating = 4.098039215686274
user id =  372  rating = 4.303030303030303
user id =  373  rating = 3.7339055793991416
user id =  374  rating = 3.31021897810219
user id =  375  rating = 3.6785714285714284
user id =  376  rating = 3.7333333333333334
user id =  377  rating = 3.909090909090909
user id =  378  rating = 3.424
user id =  379  rating = 3.989795918367347
user id =  380  rating = 3.197530864197531
user id =  381  rating = 3.811023622047244
user id =  382  rating = 3.4716981132075473
user id =  383  rating = 4.380281690140845
user id =  384  rating = 4.136363636363637
user id =  385  rating = 3.295373665480427
user id =  386  rating = 3.652173913043478
user id =  387  rating = 3.361842105263158
user id =  388  rating = 4.173076923076923
user id =  389  rating = 3.7047970479704797
user id =  390  rating = 3.838709677419355
user id =  391  rating = 3.768595041322314
user id =  392  rating = 4.045045045045045
user id =  393  rating = 3.3370535714285716
user id =  394  rating = 3.859060402684564
user id =  395  rating = 3.8947368421052633
user id =  396  rating = 3.4074074074074074
user id =  397  rating = 3.7058823529411766
user id =  398  rating = 3.7093023255813953
user id =  399  rating = 2.93730407523511
user id =  400  rating = 3.590909090909091
user id =  401  rating = 3.1176470588235294
user id =  402  rating = 3.8970588235294117
user id =  403  rating = 3.68
user id =  404  rating = 3.25
user id =  405  rating = 1.8344640434192674
user id =  406  rating = 3.5321637426900585
user id =  407  rating = 3.4690265486725664
user id =  408  rating = 3.740740740740741
user id =  409  rating = 3.5911330049261085
user id =  410  rating = 3.0357142857142856
user id =  411  rating = 3.7758620689655173
user id =  412  rating = 3.9411764705882355
user id =  413  rating = 3.66
user id =  414  rating = 3.88
user id =  415  rating = 4.166666666666667
user id =  416  rating = 3.845841784989858
user id =  417  rating = 3.2465753424657535
user id =  418  rating = 2.9
user id =  419  rating = 4.21875
user id =  420  rating = 4.166666666666667
user id =  421  rating = 3.8548387096774195
user id =  422  rating = 3.463917525773196
user id =  423  rating = 3.578125
user id =  424  rating = 3.3636363636363638
user id =  425  rating = 2.9558823529411766
user id =  426  rating = 3.8316831683168315
user id =  427  rating = 4.548387096774194
user id =  428  rating = 3.9272727272727272
user id =  429  rating = 3.393719806763285
user id =  430  rating = 3.5538461538461537
user id =  431  rating = 3.380952380952381
user id =  432  rating = 3.7096774193548385
user id =  433  rating = 3.5121951219512195
user id =  434  rating = 3.7045454545454546
user id =  435  rating = 3.316622691292876
user id =  436  rating = 3.7517241379310344
user id =  437  rating = 3.581749049429658
user id =  438  rating = 4.0606060606060606
user id =  439  rating = 3.7096774193548385
user id =  440  rating = 4.176470588235294
user id =  441  rating = 3.5
user id =  442  rating = 3.125874125874126
user id =  443  rating = 3.375
user id =  444  rating = 3.7916666666666665
user id =  445  rating = 1.9851851851851852
user id =  446  rating = 2.75
user id =  447  rating = 3.597122302158273
user id =  448  rating = 3.3421052631578947
user id =  449  rating = 3.7466666666666666
user id =  450  rating = 3.8648148148148147
user id =  451  rating = 2.7346938775510203
user id =  452  rating = 3.412621359223301
user id =  453  rating = 3.2884615384615383
user id =  454  rating = 2.9788135593220337
user id =  455  rating = 3.502645502645503
user id =  456  rating = 3.456221198156682
user id =  457  rating = 4.025270758122744
user id =  458  rating = 3.6885245901639343
user id =  459  rating = 3.3813559322033897
user id =  460  rating = 3.411764705882353
user id =  461  rating = 3.0
user id =  462  rating = 4.0
user id =  463  rating = 2.8646616541353382
user id =  464  rating = 4.037735849056604
user id =  465  rating = 3.4375
user id =  466  rating = 3.4653465346534653
user id =  467  rating = 3.6818181818181817
user id =  468  rating = 3.993006993006993
user id =  469  rating = 4.534883720930233
user id =  470  rating = 3.5789473684210527
user id =  471  rating = 3.3870967741935485
user id =  472  rating = 4.228136882129277
user id =  473  rating = 3.914285714285714
user id =  474  rating = 4.08256880733945
user id =  475  rating = 3.6
user id =  476  rating = 3.3734939759036147
user id =  477  rating = 4.457142857142857
user id =  478  rating = 3.415929203539823
user id =  479  rating = 3.4207920792079207
user id =  480  rating = 3.7333333333333334
user id =  481  rating = 3.982142857142857
user id =  482  rating = 3.423076923076923

user id =  543  rating = 3.532994923857868
user id =  544  rating = 2.806451612903226
user id =  545  rating = 3.506172839506173
user id =  546  rating = 3.8983050847457625
user id =  547  rating = 3.652173913043478
user id =  548  rating = 3.670967741935484
user id =  549  rating = 3.72
user id =  550  rating = 3.675
user id =  551  rating = 3.802395209580838
user id =  552  rating = 3.0952380952380953
user id =  553  rating = 4.17
user id =  554  rating = 3.5701754385964914
user id =  555  rating = 4.019230769230769
user id =  556  rating = 4.204545454545454
user id =  557  rating = 3.7547169811320753
user id =  558  rating = 4.2
user id =  559  rating = 3.5789473684210527
user id =  560  rating = 3.396039603960396
user id =  561  rating = 3.0252100840336134
user id =  562  rating = 3.5416666666666665
user id =  563  rating = 3.7666666666666666
user id =  564  rating = 3.411764705882353
user id =  565  rating = 4.542857142857143
user id =  566  rating = 3.442953020134228
user id =  567  rating = 3.9548387096774196
user id =  568  rating = 3.3703703703703702
user id =  569  rating = 3.4857142857142858
user id =  570  rating = 2.6818181818181817
user id =  571  rating = 3.45
user id =  572  rating = 3.25
user id =  573  rating = 3.7450980392156863
user id =  574  rating = 3.5217391304347827
user id =  575  rating = 3.1538461538461537
user id =  576  rating = 3.5277777777777777
user id =  577  rating = 3.8031914893617023
user id =  578  rating = 2.6666666666666665
user id =  579  rating = 3.472972972972973
user id =  580  rating = 3.5531914893617023
user id =  581  rating = 4.035714285714286
user id =  582  rating = 3.274193548387097
user id =  583  rating = 4.444444444444445
user id =  584  rating = 3.5416666666666665
user id =  585  rating = 3.7375
user id =  586  rating = 3.325301204819277
user id =  587  rating = 2.9693877551020407
user id =  588  rating = 3.7422222222222223
user id =  589  rating = 3.441860465116279
user id =  590  rating = 3.5
user id =  591  rating = 3.6547619047619047
user id =  592  rating = 3.813888888888889
user id =  593  rating = 3.608974358974359
user id =  594  rating = 3.48
user id =  595  rating = 3.1979166666666665
user id =  596  rating = 3.6
user id =  597  rating = 3.6341463414634148
user id =  598  rating = 3.68
user id =  599  rating = 3.893617021276596
user id =  600  rating = 3.5842696629213484
user id =  601  rating = 3.081081081081081
user id =  602  rating = 3.793103448275862
user id =  603  rating = 3.7872340425531914
user id =  604  rating = 3.2962962962962963
user id =  605  rating = 3.7555555555555555
user id =  606  rating = 3.9661016949152543
user id =  607  rating = 3.8378378378378377
user id =  608  rating = 3.6748466257668713
user id =  609  rating = 2.392857142857143
user id =  610  rating = 3.7333333333333334
user id =  611  rating = 3.8333333333333335
user id =  612  rating = 3.3703703703703702
user id =  613  rating = 4.321428571428571
user id =  614  rating = 3.128205128205128
user id =  615  rating = 3.8640776699029127
user id =  616  rating = 3.627906976744186
user id =  617  rating = 2.6203703703703702
user id =  618  rating = 3.287037037037037
user id =  619  rating = 3.50561797752809
user id =  620  rating = 3.827272727272727
user id =  621  rating = 3.5497076023391814
user id =  622  rating = 3.3903508771929824
user id =  623  rating = 3.7333333333333334
user id =  624  rating = 3.5319148936170213
user id =  625  rating = 3.4339622641509435
user id =  626  rating = 2.34375
user id =  627  rating = 3.292817679558011
user id =  628  rating = 4.703703703703703
user id =  629  rating = 4.082644628099174
user id =  630  rating = 3.324074074074074
user id =  631  rating = 3.1
user id =  632  rating = 3.6610169491525424
user id =  633  rating = 3.310344827586207
user id =  634  rating = 3.3703703703703702
user id =  635  rating = 3.264705882352941
user id =  636  rating = 4.45
user id =  637  rating = 2.4903846153846154
user id =  638  rating = 3.537313432835821
user id =  639  rating = 2.9594594594594597
user id =  640  rating = 4.229357798165138
user id =  641  rating = 4.125
user id =  642  rating = 3.6226415094339623
user id =  643  rating = 3.737864077669903
user id =  644  rating = 4.0
user id =  645  rating = 3.959016393442623
user id =  646  rating = 2.9473684210526314
user id =  647  rating = 3.8275862068965516
user id =  648  rating = 3.259259259259259
user id =  649  rating = 3.7916666666666665
user id =  650  rating = 3.1543408360128615
user id =  651  rating = 3.2857142857142856
user id =  652  rating = 3.1363636363636362
user id =  653  rating = 2.6925795053003534
user id =  654  rating = 3.687074829931973
user id =  655  rating = 2.908029197080292
user id =  656  rating = 2.5416666666666665
user id =  657  rating = 3.2413793103448274
user id =  658  rating = 3.732394366197183
user id =  659  rating = 3.7905759162303663
user id =  660  rating = 2.5848214285714284
user id =  661  rating = 3.9173553719008263
user id =  662  rating = 3.869565217391304
user id =  663  rating = 3.5316455696202533
user id =  664  rating = 3.746987951807229
user id =  665  rating = 3.4788732394366195
user id =  666  rating = 3.6653061224489796
user id =  667  rating = 3.9574468085106385
user id =  668  rating = 3.5217391304347827
user id =  669  rating = 3.38
user id =  670  rating = 3.847826086956522
user id =  671  rating = 3.5806451612903225
user id =  672  rating = 3.2413793103448274
user id =  673  rating = 3.8857142857142857
user id =  674  rating = 3.658536585365854
user id =  675  rating = 3.7058823529411766
user id =  676  rating = 3.5844155844155843
user id =  677  rating = 3.5918367346938775
user id =  678  rating = 3.4285714285714284
user id =  679  rating = 3.661290322580645
user id =  680  rating = 4.0
user id =  681  rating = 3.227272727272727
user id =  682  rating = 3.137844611528822
user id =  683  rating = 3.2266666666666666
user id =  684  rating = 3.488372093023256
user id =  685  rating = 2.05
user id =  686  rating = 4.563380281690141
user id =  687  rating = 3.4761904761904763
user id =  688  rating = 4.833333333333333
user id =  689  rating = 3.8333333333333335
user id =  690  rating = 3.1478260869565218
user id =  691  rating = 4.21875
user id =  692  rating = 3.275
user id =  693  rating = 3.1363636363636362
user id =  694  rating = 4.1528662420382165
user id =  695  rating = 3.289473684210526
user id =  696  rating = 3.9310344827586206
user id =  697  rating = 3.7142857142857144
user id =  698  rating = 2.84251968503937
user id =  699  rating = 3.1476510067114094
user id =  700  rating = 3.6666666666666665
user id =  701  rating = 4.212121212121212
user id =  702  rating = 2.4516129032258065
user id =  703  rating = 3.5319148936170213
user id =  704  rating = 3.7777777777777777
user id =  705  rating = 3.710526315789474
user id =  706  rating = 3.310344827586207
user id =  707  rating = 3.4957627118644066
user id =  708  rating = 3.2
user id =  709  rating = 3.572463768115942
user id =  710  rating = 3.697674418604651
user id =  711  rating = 3.8597285067873304
user id =  712  rating = 3.765432098765432
user id =  713  rating = 2.966666666666667
user id =  714  rating = 3.522727272727273
user id =  715  rating = 3.3832335329341316
user id =  716  rating = 3.8884758364312266
user id =  717  rating = 3.7096774193548385
user id =  718  rating = 3.6923076923076925
user id =  719  rating = 3.1044776119402986
user id =  720  rating = 3.966666666666667
user id =  721  rating = 3.5357142857142856
user id =  722  rating = 3.619047619047619
user id =  723  rating = 3.272727272727273
user id =  724  rating = 2.164705882352941
user id =  725  rating = 3.8
user id =  726  rating = 3.0
user id =  727  rating = 3.0372670807453415
user id =  728  rating = 3.576923076923077
user id =  729  rating = 2.857142857142857
user id =  730  rating = 3.236842105263158
user id =  731  rating = 3.3855421686746987
user id =  732  rating = 3.7
user id =  733  rating = 3.02803738317757
user id =  734  rating = 3.609375
user id =  735  rating = 3.3207547169811322
user id =  736  rating = 3.0
user id =  737  rating = 3.9696969696969697
user id =  738  rating = 3.675675675675676
user id =  739  rating = 3.6
user id =  740  rating = 3.4
user id =  741  rating = 3.4615384615384617
user id =  742  rating = 3.4615384615384617
user id =  743  rating = 3.6857142857142855
user id =  744  rating = 3.8518518518518516
user id =  745  rating = 3.1
user id =  746  rating = 3.6417910447761193
user id =  747  rating = 4.054607508532423
user id =  748  rating = 3.7222222222222223
user id =  749  rating = 3.622950819672131
user id =  750  rating = 3.090909090909091
user id =  751  rating = 3.5416666666666665
user id =  752  rating = 3.2054794520547945
user id =  753  rating = 3.5964912280701755
user id =  754  rating = 3.3823529411764706
user id =  755  rating = 3.1052631578947367
user id =  756  rating = 3.1926605504587156
user id =  757  rating = 3.3674698795180724
user id =  758  rating = 3.876750700280112
user id =  759  rating = 4.0625
user id =  760  rating = 3.2439024390243905
user id =  761  rating = 2.8484848484848486
user id =  762  rating = 3.0476190476190474
user id =  763  rating = 3.7829457364341086
user id =  764  rating = 3.688073394495413
user id =  765  rating = 4.086956521739131
user id =  766  rating = 3.354285714285714
user id =  767  rating = 4.4324324324324325
user id =  768  rating = 3.265625
user id =  769  rating = 3.0689655172413794
user id =  770  rating = 4.296875
user id =  771  rating = 3.7142857142857144
user id =  772  rating = 4.0
user id =  773  rating = 3.279503105590062
user id =  774  rating = 2.0580357142857144
user id =  775  rating = 3.7857142857142856
user id =  776  rating = 3.466666666666667
user id =  777  rating = 4.055555555555555
user id =  778  rating = 2.953846153846154
user id =  779  rating = 3.918918918918919
user id =  780  rating = 3.8727272727272726
user id =  781  rating = 3.7857142857142856
user id =  782  rating = 2.788793103448276
user id =  783  rating = 3.8666666666666667
user id =  784  rating = 3.8461538461538463
user id =  785  rating = 3.7037037037037037
user id =  786  rating = 3.871794871794872
user id =  787  rating = 3.1403508771929824
user id =  788  rating = 3.3413654618473894
user id =  789  rating = 3.6666666666666665
user id =  790  rating = 3.017316017316017
user id =  791  rating = 3.8
user id =  792  rating = 3.127659574468085
user id =  793  rating = 3.5090909090909093
user id =  794  rating = 4.3076923076923075
user id =  795  rating = 3.1320754716981134
user id =  796  rating = 3.600558659217877
user id =  797  rating = 2.6538461538461537
user id =  798  rating = 3.3263598326359833
user id =  799  rating = 4.0
user id =  800  rating = 3.75
user id =  801  rating = 4.038461538461538
user id =  802  rating = 3.493333333333333
user id =  803  rating = 3.090909090909091
user id =  804  rating = 3.6656626506024095
user id =  805  rating = 3.347985347985348
user id =  806  rating = 3.642857142857143
user id =  807  rating = 3.892156862745098
user id =  808  rating = 4.130434782608695
user id =  809  rating = 3.45
user id =  810  rating = 4.423076923076923
user id =  811  rating = 4.142857142857143
user id =  812  rating = 3.5
user id =  813  rating = 2.793103448275862
user id =  814  rating = 2.9714285714285715
user id =  815  rating = 3.7431693989071038
user id =  816  rating = 3.84
user id =  817  rating = 3.361111111111111
user id =  818  rating = 3.4761904761904763
user id =  819  rating = 4.071428571428571
user id =  820  rating = 3.0
user id =  821  rating = 4.338709677419355
user id =  822  rating = 3.12
user id =  823  rating = 4.005405405405406
user id =  824  rating = 2.6
user id =  825  rating = 3.613793103448276
user id =  826  rating = 3.8260869565217392
user id =  827  rating = 3.25
user id =  828  rating = 3.1153846153846154
user id =  829  rating = 3.546875
user id =  830  rating = 3.7452830188679247
user id =  831  rating = 3.5205479452054793
user id =  832  rating = 2.96
user id =  833  rating = 3.056179775280899
user id =  834  rating = 3.925925925925926
user id =  835  rating = 4.147058823529412
user id =  836  rating = 3.86
user id =  837  rating = 3.0434782608695654
user id =  838  rating = 4.118279569892473
user id =  839  rating = 3.192982456140351
user id =  840  rating = 4.137055837563452
user id =  841  rating = 3.903225806451613
user id =  842  rating = 3.740740740740741
user id =  843  rating = 2.735294117647059
user id =  844  rating = 3.506172839506173
user id =  845  rating = 3.129032258064516
user id =  846  rating = 3.740740740740741
user id =  847  rating = 3.0342465753424657
user id =  848  rating = 4.286666666666667
user id =  849  rating = 4.869565217391305
user id =  850  rating = 4.529411764705882
user id =  851  rating = 3.45933014354067
user id =  852  rating = 3.4693877551020407
user id =  853  rating = 2.975609756097561
user id =  854  rating = 3.2119815668202767
user id =  855  rating = 3.347826086956522
user id =  856  rating = 3.423076923076923
user id =  857  rating = 3.272727272727273
user id =  858  rating = 3.4285714285714284
user id =  859  rating = 3.8461538461538463
user id =  860  rating = 3.23943661971831
user id =  861  rating = 4.0
user id =  862  rating = 4.363636363636363
user id =  863  rating = 3.121495327102804
user id =  864  rating = 3.82312925170068
user id =  865  rating = 2.287878787878788
user id =  866  rating = 2.7
user id =  867  rating = 4.2631578947368425
user id =  868  rating = 2.951923076923077
user id =  869  rating = 2.872340425531915
user id =  870  rating = 3.453531598513011
user id =  871  rating = 3.4956521739130433
user id =  872  rating = 3.380281690140845
user id =  873  rating = 2.9
user id =  874  rating = 3.823529411764706
user id =  875  rating = 4.191011235955056
user id =  876  rating = 4.190476190476191
user id =  877  rating = 3.8271604938271606
user id =  878  rating = 3.2686567164179103
user id =  879  rating = 3.689655172413793
user id =  880  rating = 3.426630434782609
user id =  881  rating = 3.3204633204633205
user id =  882  rating = 4.0510948905109485
user id =  883  rating = 3.925373134328358
user id =  884  rating = 3.7209302325581395
user id =  885  rating = 3.3137254901960786
user id =  886  rating = 3.3625
user id =  887  rating = 3.9239766081871346
user id =  888  rating = 4.3
user id =  889  rating = 3.4355828220858897
user id =  890  rating = 3.857142857142857
user id =  891  rating = 4.127659574468085
user id =  892  rating = 4.0
user id =  893  rating = 3.4237288135593222
user id =  894  rating = 3.636734693877551
user id =  895  rating = 3.75
user id =  896  rating = 2.9806629834254146
user id =  897  rating = 3.962162162162162
user id =  898  rating = 3.5
user id =  899  rating = 3.525925925925926
user id =  900  rating = 2.5555555555555554
user id =  901  rating = 3.8548387096774195
user id =  902  rating = 3.4489795918367347
user id =  903  rating = 3.8529411764705883
user id =  904  rating = 3.74468085106383
user id =  905  rating = 3.275
user id =  906  rating = 3.8048780487804876
user id =  907  rating = 4.571428571428571
user id =  908  rating = 3.554054054054054
user id =  909  rating = 4.346153846153846
user id =  910  rating = 3.1666666666666665
user id =  911  rating = 3.806122448979592
user id =  912  rating = 3.811320754716981
user id =  913  rating = 3.522727272727273
user id =  914  rating = 3.0869565217391304
user id =  915  rating = 3.1153846153846154
user id =  916  rating = 3.365930599369085
user id =  917  rating = 3.5428571428571427
user id =  918  rating = 3.349514563106796
user id =  919  rating = 3.4700460829493087
user id =  920  rating = 3.230769230769231
user id =  921  rating = 3.272727272727273
user id =  922  rating = 3.37007874015748
user id =  923  rating = 4.148648648648648
user id =  924  rating = 3.7560975609756095
user id =  925  rating = 3.125
user id =  926  rating = 3.3
user id =  927  rating = 3.691666666666667
user id =  928  rating = 4.6875
user id =  929  rating = 3.693877551020408
user id =  930  rating = 2.9682539682539684
user id =  931  rating = 3.721311475409836
user id =  932  rating = 3.966804979253112
user id =  933  rating = 2.6467391304347827
user id =  934  rating = 3.7011494252873565
user id =  935  rating = 3.923076923076923
user id =  936  rating = 3.7464788732394365
user id =  937  rating = 3.375
user id =  938  rating = 3.2685185185185186
user id =  939  rating = 4.26530612244898
user id =  940  rating = 3.457943925233645
user id =  941  rating = 4.045454545454546
user id =  942  rating = 4.265822784810126
user id =  943  rating = 3.4107142857142856
Occupations =  ['technician' 'other' 'writer' 'executive' 'administrator' 'student'
 'lawyer' 'educator' 'scientist' 'entertainment' 'programmer' 'librarian'
 'homemaker' 'artist' 'engineer' 'marketing' 'none' 'healthcare' 'retired'
 'salesman' 'doctor']
males are more dominant in  technician
males are more dominant in  other
males are more dominant in  writer
males are more dominant in  executive
males are more dominant in  administrator
males are more dominant in  student
males are more dominant in  lawyer
males are more dominant in  educator
males are more dominant in  scientist
males are more dominant in  entertainment
males are more dominant in  programmer

females are more dominant in  librarian
females are more dominant in  homemaker
males are more dominant in  artist
males are more dominant in  engineer
males are more dominant in  marketing
males are more dominant in  none
females are more dominant in  healthcare
males are more dominant in  retired
males are more dominant in  salesman
males are more dominant in  doctor
number of male users:
670
number of female users:
273

**Question 4**:
- produce a 1-page document that uses a combination of text, tables, and figures that provide some interesting insights about the Movie Lens data. You should feel free to use outside sources to produce the report, as long as you acknowledge your sources.

In [ ]:
print("hello")

## Lab 3.C. HTML Data

In this part of the lab, you will be also be working on an exercise that is a slightly modified and shortened version of https://github.com/cs109/2015/blob/master/Lectures/02-DataScrapingQuizzes.ipynb. In particular, you will learn how to load and analyze html data.

HTML:
* HyperText Markup Language
* standard for creating webpages
* HTML tags 
    - have angle brackets
    - typically come in pairs

Below is an example for a minimal webpage defined in HTML tags. The root tag is <html> and then you have the <head> tag. This part of the page typically includes the title of the page and might also have other meta information like the author or keywords that are important for search engines. The <body> tag marks the actual content of the page. You can play around with the <h2> tag trying different header levels. They range from 1 to 6.

In [ ]:
htmlString = """<!DOCTYPE html>
<html>
  <head>
    <title>This is a title</title>
  </head>
  <body>
    <h2> Test </h2>
    <p>Hello world!</p>
  </body>
</html>"""

htmlOutput = HTML(htmlString)
htmlOutput

Useful Tags:

* heading
`<h1></h1> ... <h6></h6>`

* paragraph
`<p></p>` 

* line break
`<br>` 

* link with attribute

`<a href="http://www.example.com/">An example link</a>`

### Scraping with Python:

Example of a simple webpage: http://www.crummy.com/software/BeautifulSoup

Good news: 
    - some browsers help
    - look for: inspect element
    - need only basic html
    - try 'Ctrl-Shift I' in Chrome
    - try 'Command-Option I' in Safari
   
Different useful libraries:
    - urllib
    - beautifulsoup
    - pattern
    - soupy
    - LXML
    - ...
 
The following cell just defines a url as a string and then reads the data from that url using the `urllib` library. If you uncomment the print command you see that we got the whole HTML content of the page into the string variable source.

In [ ]:
url = 'http://www.crummy.com/software/BeautifulSoup'
source = requests.get(url).text
print(source)

**Question 5**:

* Is the word 'Alice' mentioned on the beautiful soup homepage?
* How often does the word 'Soup' occur on the site?
    - hint: use `.count()`
* At what index occurs the substring 'alien video games' ?
    - hint: use `.find()`

In [ ]:
## is 'Alice' in source?

## count occurences of 'Soup'

## find index of 'alien video games'

**Beautiful Soup**

* designed to make your life easier
* many good functions for parsing html code

Some examples:

In [ ]:
## get bs4 object
soup = bs4.BeautifulSoup(source)
 
## compare the two print statements
#print soup
#print soup.prettify()

## show how to find all a tags
soup.findAll('a')

## ***Why does this not work? ***
#soup.findAll('Soup')

More examples:

In [ ]:
## get attribute value from an element:
## find tag: this only returns the first occurrence, not all tags in the string
first_tag = soup.find('a')

## get attribute `href`
first_tag.get('href')

## get all links in the page
link_list = [l.get('href') for l in soup.findAll('a')]
link_list

In [ ]:
## filter all external links
# create an empty list to collect the valid links
external_links = []

# write a loop to filter the links
# if it starts with 'http' we are happy
for l in link_list:
    if l[:4] == 'http':
        external_links.append(l)

# this throws an error! It says something about 'NoneType'

In [ ]:
# lets investigate. Have a close look at the link_list:
link_list

# Seems that there are None elements!
# Let's verify
#print sum([l is None for l in link_list])

# So there are two elements in the list that are None!

In [ ]:
# Let's filter those objects out in the for loop
external_links = []

# write a loop to filter the links
# if it is not None and starts with 'http' we are happy
for l in link_list:
    if l is not None and l[:4] == 'http':
        external_links.append(l)
        
external_links

*Note*: The above `if` condition works because of lazy evaluation in Python. The `and` statement becomes `False` if the first part is `False`, so there is no need to ever evaluate the second part. Thus a `None` entry in the list gets never asked about its first four characters.

In [ ]:
# and we can put this in a list comprehension as well, it almost reads like 
# a sentence.

[l for l in link_list if l is not None and l.startswith('http')]

Parsing the Tree:

In [ ]:
# redifining `s` without any line breaks
s = """<!DOCTYPE html><html><head><title>This is a title</title></head><body><h3> Test </h3><p>Hello world!</p></body></html>"""
## get bs4 object
tree = bs4.BeautifulSoup(s)

## get html root node
root_node = tree.html

## get head from root using contents
head = root_node.contents[0]

## get body from root
body = root_node.contents[1]

## could directly access body
tree.body

**Question 6**:

* Find the `h3` tag by parsing the tree starting at `body`
* Create a list of all __Hall of Fame__ entries listed on the Beautiful Soup webpage
    - hint: it is the only unordered list in the page (tag `ul`)

In [ ]:
## get h3 tag from body


## use ul as entry point


## get hall of fame list from entry point
## skip the first entry 

## reformat into a list containing strings
## it is ok to have a list of lists

`tmp` now is actually a list of lists containing the hall of fame entries. 
Here is some advanced Python on how to print really just one entry per list item.

The cool things about this are: 
* The use of `""` to just access the `join` function of strings.
* The `join` function itself
* that you can actually have two nested for loops in a list comprehension

In [ ]:
test =  ["".join(str(a) for a in sublist) for sublist in tmp]
print('\n'.join(test))

**Question 7**:
- Explain in detail what is Python doing in the previous line

**Question 8**:
- Plot a histogram of the count of the 20 most common words in the html file
- Plot a histogram of the count of the 20 most common words in the visible part (what is displayed in the browser) of the html file

**Deliverable**: For Lab 3.B and 3.C submit a modified version of this .ipynb file that contains all the answers to the quesitons